---
title: "Regression"
bibliography: references.bib
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
editor_options: 
  chunk_output_type: console
---

*Das* wichtigste Verfahren im allgemeinen linearen Modell, in dem wir uns in der geisteswissenschaftlich-medizinischen Forschung anscheinend ausschließlich aufhalten, ist die lineare Regression. Mit ihr können wir unter bestimmten Voraussetzungen lineare Zusammenhänge beschreiben, sowohl was die Stärke als auch die Größe eines Zusammenhangs angeht. Und nicht nur das, denn das Verfahren kann so erweitert werden, dass wir Mittelwertsunterschiede testen können (daher ist die Aufteilung dieser Website etwas irreführend).

# Korrelation
Mit der [**Korrelation**](korrelation.html) können wir die **Stärke** eines linearen Zusammenhangs beschreiben. Wie stark hängen z.B. die Durchschnittstemperatur mit der Anzahl der Mückenstiche zusammen? Diese Frage beantwortet die Korrelation. Als Ergebnis erhalten wir einen Korrelationskoeffizienten, typischerweise zwischen 0 und 1, der uns eben angibt, ob ein Zusammenhang gar nicht bis schwach vorhanden ist (Werte nahe 0), oder ob ein Zusammenhang sehr stark ist (Werte nahe 1). Die Stärke eines Zusammenhangs aber sagt noch nichts über die *Größe* dieses Zusammenhangs aus, denn ein Zusammenhang kann sehr stark sein, also das Verhältnis von Prädiktor zu Kriterium fast linear, jedoch die Größe des Effekts minimal. Interessiert man sich für die Größe eines linearen Zusammenhangs, ist man mit dem Verfahren der **linearen Regression** (s.u.) gut bedient.

# Lineare Regression
Mit der [**linearen Regression**](lineare-regression.html) kann man die **Größe** eines linearen Zusammenhangs zwischen beliebig vielen Prädiktoren und einem Kriterium beschreiben und Vorhersagen treffen. Dabei kann man sowohl die Größe eines Zusammenhangs ermitteln als auch die Güte des Modells, d.h. ob das gefundene Modell die Daten gut beschreibt, oder ob da etwas nicht ganz stimmt. Als eines der grundlegenden statistischen Verfahren lohnt es sich, dieses gut zu kennen und sicher durchführen zu können.

# Repeated Measures Correlation
Die "normale" Korrelation berechnet die Stärke eines Zusammenhangs nur zwischen zwei unabhängigen Variablen. Was ist aber, wenn ich den Zusammenhang zwischen zwei Variablen zu mehreren Messzeitpunkten erfasst habe? Die Messungen sind ja dann nicht mehr unabhängig und ich habe dann für bspw. einen Probanden mehrere Variablenpaare vorliegen. Hier kommt die *repeated measures correlation* (**RM Korrelation**) ins Spiel, die genau für diesen Fall vorgesehen ist. Sie nimmt grob gesagt die Variablenpaare zu den jeweiligen Messzeitpunkten und spuckt am Ende auch einen Korrelationskoeffizienten aus. Trotz der Mächtigkeit dieses Verfahrens und seiner weitgreifenden Anwendungsmöglichkeiten, scheint das Verfahren in der Praxis kaum etabliert zu sein.

# Multilevel Linear Models
**Multilevel Linear Models** (MLM) sind lineare Regressionen auf Steroiden. Beim genaueren Hinsehen ergeben sich für unsere Anwendungen der linearen Regression teilweise ernsthafte Probleme. Eine [Voraussetzung im allgemeinen linearen Modell](voraussetzungen.html) ist bspw. die Unabhängigkeit der Residuen. Aber in vielen Fällen kann diese Annahme verletzt sein. Ein klassisches Beispiel sind messwiederholte Daten, bei denen ich pro Proband mehrere Messzeitpunkte erhebe. Jeder Proband für sich macht aber wahrscheinlich individuelle Fehler, weshalb die Residuen (die Fehler) eben nicht unabhängig sind. Natürlich könnten wir mithilfe der ANOVA mit Messwiederholung stumpf die Mittelwerte prüfen, aber diese hat ernstzunehmende Einschränkungen. Stattdessen kann man die Daten innerhalb verschiedener Ebenen (*levels*) einteilen und Prädiktoren gezielt den einzelnen Ebenen zuweisen. MLM sind ein elegantes und ungalublich breit einsetzbares wie mächtiges Verfahren.