<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Einfaktorielle ANOVA</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="images/broom.ico">

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Chamber of Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Allgemeines
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="software.html">Software</a>
    </li>
    <li>
      <a href="r-basics.html">R Basics</a>
    </li>
    <li>
      <a href="stil.html">Stil</a>
    </li>
    <li>
      <a href="pakete.html">Pakete</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mittelwerte vergleichen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mittelwerte-vergleichen.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">t-Tests</li>
    <li>
      <a href="t-test-einstichprobe.html">Bei einer Stichprobe</a>
    </li>
    <li>
      <a href="t-test-unabhaengig.html">Bei unabhängigen Stichproben</a>
    </li>
    <li>
      <a href="t-test-abhaengig.html">Bei abhängigen Stichproben</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ANOVAs</li>
    <li>
      <a href="einfaktorielle-anova.html">Einfaktorielle ANOVA</a>
    </li>
    <li>
      <a href="faktorielle-anova.html">Faktorielle ANOVA</a>
    </li>
    <li class="dropdown-header">ANCOVA</li>
    <li class="dropdown-header">Repeated Measures ANOVA</li>
    <li class="dropdown-header">Mixed ANOVA</li>
    <li>
      <a href="kontraste.html">Geplante Kontraste</a>
    </li>
    <li>
      <a href="post-hoc-tests.html">Post-hoc-Tests</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-question"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="voraussetzungen.html">Voraussetzungen im GLM</a>
    </li>
    <li>
      <a href="zentraler-grenzwertsatz.html">Zentraler Grenzwertsatz</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Einfaktorielle ANOVA</h1>

</div>


<p><img src="images/roller-coaster_r.jpg" /></p>
<p>Mit einer einfaktoriellen Varianlzanalyse (ANOVA) kann man die Mittelwerte von mehr als zwei Gruppen miteinander vergleichen. Da die einfaktorielle ANOVA ein Omnibus-Test ist, und so nur anzeigt, ob irgendwo ein signifikanter Unterschied zwischen den betrachteten Mittelwerten besteht, nutzt man entweder Kontraste oder Post-hoc-Tests, um herauszufinden, welche Mittelwerte sich letztendlich signifikant voneinander unterscheiden.</p>
<div id="pakete" class="section level1">
<h1>Pakete</h1>
<p>Alle Berechnungen und Abbildungen können wir mit unseren <a href="pakete.html">Standardpaketen</a> durchführen. Wir benötigen das <code>tidyverse</code> zum Data Wrangling und zur Visualisierung der Daten. <code>haven</code> benötigen wir für den Import von SPSS-Dateien und <code>rstatix</code> für statistische Analysen.</p>
<pre class="r"><code>library(tidyverse)
library(haven)
library(rstatix)</code></pre>
</div>
<div id="beispiel" class="section level1">
<h1>Beispiel</h1>
<p>Begeben wir uns ins <a href="https://www.phantasialand.de/de/">Phantasialand</a> in Brühl bei Köln. Auch Forscher brauchen mal Spaß – und wo könnte man sich den besser holen? Natürlich lässt sich das Bestreben nach wissenschaftlichem Fortschritt auch bei Besuchen von Freizeitparks nicht abstellen. So fällt uns beispielsweise auf, dass selbst im Phantasialand, nicht alle Besucher gleich viel Spaß haben. Es gibt sehr viele, die mit lachenden Gesichtern durch den Park laufen, doch auch jene, die ihre Mundwinkel der Schwerkraft hingeben. Woran könnte das liegen? Eine Hypothese könnte doch das Gewicht des Handgepäcks sein. Vielleicht haben Besucher mit wenig Handgepäck mehr Spaß, weil sie weniger zu tragen haben? Wir möchten also untersuchen, ob die Größe des Handgepäcks einen Einfluss auf die Freude der Besucher hat. Dazu haben wir viele Besucher mit vier unterschiedlichen Arten von Handgepäck nach ihrer derzeitigen empfundenen Freude gefragt.</p>
<div id="klassisch" class="section level2">
<h2>Klassisch</h2>
<p>Die Daten dieser kleinen Erhebung sind in der Datei <code>phantasialand.sav</code>. Die Spalte <code>id</code> ist die ID des Besuchers, in der Spalte <code>backpack</code> ist angegeben, mit welchem Handgepäck der Besucher oder die Besucherin unterwegs war. Wir unterscheiden vier Faktorstufen: “None” = kein Handgepäck, “Light” = leichtes, “Heavy” steht für schweres und “Handcart” steht für Bollerwagen. In der Spalte <code>joy</code> wurde die zu dem Zeitpunkt empfundene Freude des Besuchers eingetragen.</p>
<pre class="r"><code>phantasialand &lt;- read_spss(&quot;data/phantasialand.sav&quot;)

phantasialand &lt;- phantasialand %&gt;% 
  mutate(backpack = as_factor(backpack))

phantasialand</code></pre>
<pre><code>## # A tibble: 186 x 3
##    id    backpack   joy
##    &lt;chr&gt; &lt;fct&gt;    &lt;dbl&gt;
##  1 1     Light        5
##  2 2     Light        7
##  3 3     Handcart     3
##  4 4     Heavy        6
##  5 5     Heavy        3
##  6 6     Heavy        6
##  7 7     Handcart     4
##  8 8     None        10
##  9 9     None         9
## 10 10    Handcart     5
## # ... with 176 more rows</code></pre>
<p>Wie immer, wenn wir SPSS-Daten mit vergebenen Werte-Labels importieren, schützt das Paket <code>haven</code> für uns die Information der Levels und der Labels. In der Variable <code>backpack</code> haben wir also direkt nach dem Import sowohl die Levels (Zahlen) als auch die Labels (Bezeichnungen). Wir arbeiten auch hier, wie immer, mit ordentlichen Faktoren weiter und überführen alle Werte dieser Variablen mit der Funktion <code>as_factor()</code> in Faktoren.</p>
<p>Wir haben also vier Grupen, deren Unterschiede in der mittlere Freude wir untersuchen wollen. Dazu nutzen wir eine einfaktorielle Varianzanalyse mit dem Zwischensubjektfaktor “backpack” mit vier Faktorstufen (“None”, “Light”, “Heavy” und “Handcart”) und der abhängigen Variable “joy”.</p>
<div id="voraussetzungen" class="section level3">
<h3>Voraussetzungen</h3>
<p>Es gelten die üblichen <a href="voraussetzungen.html">Voraussetzungen des GLM</a>.</p>
</div>
<div id="eda" class="section level3">
<h3>EDA</h3>
<p>Auch hier betrachten wir die Daten erstmal, bevor wir irgendwelche Analysen durchführen. Beobachtet man verschiedene Gruppen, macht es Sinn, die Ausgabe der statistischen Kennwerte für jede Gruppe durchzuführen.</p>
<pre class="r"><code>phantasialand %&gt;% 
  group_by(backpack) %&gt;% 
  get_summary_stats()</code></pre>
<pre><code>## # A tibble: 4 x 14
##   backpack variable     n   min   max median    q1    q3   iqr   mad  mean    sd
##   &lt;fct&gt;    &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 None     joy         42     6    10    9.5     8 10     2    0.741  9.07  1.14
## 2 Light    joy         53     3    10    7       6  8     2    1.48   7.06  1.57
## 3 Heavy    joy         56     3    10    6.5     6  7.25  1.25 0.741  6.46  1.63
## 4 Handcart joy         35     0     5    3       2  4     2    1.48   2.63  1.40
## # ... with 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<p><img src="einfaktorielle-anova_files/figure-html/unnamed-chunk-6-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Wir bekommen den ersten Wind in den Segeln unserer Hypothese. Im Mittel scheinen Besucher des Phantasialands mehr Spaß zu haben, wenn sie weniger Gepäck tragen müssen. Aufgrund der Gruppengröße (jeweils <span class="math inline">\(n &gt; 30\)</span>) und des zentralen Grenzwertsatzes, müssen wir uns um die <a href="voraussetzungen.html">Voraussetzung der Normalverteilung</a> keine Gedanken machen. Im Boxplot der Daten sind leicht unterschiedliche Varianzen pro Faktorstufe zu erkennen. Um sicherzugehen, dass wir die Voraussetzung der Varianzhomogenität nicht verletzen, können wir einen Levene-Test berechnen.</p>
<pre class="r"><code>phantasialand %&gt;% 
  levene_test(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic     p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1     3   182      1.36 0.256</code></pre>
<p>Da der Levene-Test nicht signifikant ist (<span class="math inline">\(p = .256\)</span>), gehen wir davon aus, dass sich die Varianzen der Faktorstufen nicht signifikant voneinander unterscheiden. Wir dürfen also eine ganz normale einfaktorielle ANOVA berechnen. Falls sich die Varianzen signifikant voneinander unterscheiden sollten, gibt es bei der einfaktoriellen Varianzanalyse mehrere Aletrnativen (<a href="#robust">s.u.</a>).</p>
</div>
<div id="durchführung" class="section level3">
<h3>Durchführung</h3>
<p>Die eigentliche Durchführung ist kurz und schmerzlos und wird mit der Funktion <code>anova_test()</code> durchgeführt. Wir haben hier zwei Möglichkeiten unser gewünschtes Modell zu definieren. Zum einen können wir es als Regressions-Formel definieren. Dabei steht die abhängige Variable auf der linken Seite und die unabhängige(n) auf der rechten; getrennt durch eine <code>~</code> (Tilde). Zum anderen können wir die abhängige und unabhängige Variable direkt als Funktionsargumente angeben. Dieses Vorgehen bietet sich vor allem bei komplexeren Versuchsdesigns an, wie etwa ANOVAs mit Messwiederholungen oder gemischte ANOVAs. Egal, für welche Möglichkeit man sich entscheidet, die Ergebnisse sind immer gleich.</p>
<pre class="r"><code># Formelschreibweise
phantasialand %&gt;% 
  anova_test(joy ~ backpack)

# Funktionsargumente
phantasialand %&gt;% 
  anova_test(dv = joy, between = backpack)</code></pre>
<p>Ich entscheide mich bei einfachen Designs immer für die Formelschreibweise, weil sie wesentlich schneller getippt ist.</p>
<pre class="r"><code>phantasialand %&gt;% 
  anova_test(joy ~ backpack)</code></pre>
<pre><code>## ANOVA Table (type II tests)
## 
##     Effect DFn DFd       F        p p&lt;.05   ges
## 1 backpack   3 182 126.164 3.14e-44     * 0.675</code></pre>
<p>Da <span class="math inline">\(p &lt; .05\)</span> ist das Ergebis signifikant. An dieser Stelle können wir also die Aussage treffen, dass sich die mittlere von den Besuchern empfundene Freude zwischen den Faktorstufen signifikant voneinander unterscheidet. Jetzt haben wir nur ein Problem: Welche Gruppe unterscheidet sich denn von welcher? Die ANOVA ist erstmal nur ein <strong>Omnibus-Test</strong>, d.h., dass wir eine Aussage darüber treffen, ob sich die Mittelwerte der Gruppen überhaupt irgendwo unterscheiden. Wo genau, dass kann man auf zwei Arten klären:</p>
<ol style="list-style-type: decimal">
<li>mit Post-hoc-Tests und</li>
<li>mit geplanten Kontrasten</li>
</ol>
<p>Post-hoc-Tests setzt man in der Regel ein, wenn man noch keine Hypothese dazu hat, wo die Gruppen sich unterscheiden. Es werden dann, vereinfacht gesagt, alle Gruppen paarweise miteinander verglichen und die <span class="math inline">\(p\)</span>-Werte auf die Art des jeweiligen Post-hoc-Tests korrigiert. Hat man vorab eine Vermutung darüber, welche Gruppen sich unterscheiden könnten, kann man das vor der Analyse als einen <strong>Kontrast</strong> festlegen und diesen während der Analyse prüfen lassen.</p>
<p>Einen Überblick über und Empfehlungen zu Einsatzsituationen vieler Post-hoc-Tests gibt <span class="citation">Toothaker (<a href="#ref-Toothaker.1993" role="doc-biblioref">1993</a>)</span>. Ein guter Post-hoc-Test bei gleich großen Gruppengrößen und angenommener Varianzhomogenität ist der Tukey-HSD (Tukey Honest Significance Difference).</p>
<pre class="r"><code>phantasialand %&gt;% 
  tukey_hsd(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   term     group1 group2   estimate conf.low conf.high    p.adj p.adj.signif
## * &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
## 1 backpack None   Light      -2.01     -2.80    -1.23  2.20e- 9 ****        
## 2 backpack None   Heavy      -2.61     -3.39    -1.83  6.93e-14 ****        
## 3 backpack None   Handcart   -6.44     -7.32    -5.57  1.73e-14 ****        
## 4 backpack Light  Heavy      -0.592    -1.32     0.139 1.57e- 1 ns          
## 5 backpack Light  Handcart   -4.43     -5.26    -3.60  1.73e-14 ****        
## 6 backpack Heavy  Handcart   -3.84     -4.66    -3.01  2.01e-14 ****</code></pre>
<p>Aus den vielen paarweisen Vergleichen geht hervor, dass sich die Gruppe derer, die ohne Handgepäck unterwegs ist, signifikant von allen anderen Gruppen unterscheidet. Das betrifft auch die Gruppe derjenigen, die mit einem Bollerwagen (“Handcart”) unterwegs sind. Interessant ist, dass sich die Besucher mit leichtem und schwerem Handgepäck <em>nicht</em> signifikant voneinander unterscheiden. Um die ganzen Vergeliche zu durchdringen, nimmt man sich am besten den Boxplot von oben und zeichnet alle signifikanten Unterschiede ein. Man wird dann feststellen, dass wir drei homogene Gruppen haben. In der einen Gruppe sind die Besucher ohne Handgepäck (die glücklichsten), dann kommt die Gruppe derjenigen mit leichtem oder schwerem Handgepäck (etwas weniger glücklich) und “zum Schluss” diejenigen, die einen Bollerwagen ziehen müssen. Die letzte Gruppe hat mit Abstand am wenigsten Freude.</p>
</div>
<div id="berichten" class="section level3">
<h3>Berichten</h3>
<p>We found the mean experienced joy of visitors of Phantasialand to decrease with increasing weight of backpack. Those with no backpack at all had a mean joy of <span class="math inline">\(M = 9.07, SD = 1.14\)</span>. The mean joy for those with light, heavy backpack, or handcart were <span class="math inline">\(M = 7.06, SD = 1.57\)</span>, <span class="math inline">\(M = 6.46, SD = 1.63\)</span>, and <span class="math inline">\(M = 2.63, SD = 1.40\)</span> respectively. A one-way revealed the means to differ significantly, <span class="math inline">\(F(3, 182) = 126.16, p &lt; .001, \eta_G^2 = .675\)</span>. Post-hoc Tukey HSD tests revealed three homogeneous subgroups, namely those with no backpacks, those with light and heavy backpacks and those pulling a handcart.</p>
</div>
</div>
<div id="robust" class="section level2">
<h2>Robust</h2>
<p>Wenn die Voraussetzung der Varianzhomogenität bei einfaktoriellen Varianzanalysen nicht erfüllt ist, dann kann man, ähnlich wie beim <span class="math inline">\(t\)</span>-Test, die Freiheitsgrade der <span class="math inline">\(F\)</span>-Statistik korrigieren. Beim <span class="math inline">\(t\)</span>-Test hat das der Welch-Test gemacht, hier ist es dann die Welch-ANOVA.</p>
<pre class="r"><code>phantasialand %&gt;% 
  welch_anova_test(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   .y.       n statistic   DFn   DFd        p method     
## * &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;      
## 1 joy     186      159.     3  96.7 2.68e-37 Welch ANOVA</code></pre>
<p>Hier erhalten wir ebenfalls ein signifikantes Ergebnis (<span class="math inline">\(F(3, 96.7) = 159, p &lt; .001\)</span>), wodurch wir davon ausgehen können, dass sich die Mittelwerte der Gruppen unterscheiden. Generell sind jedoch Wilcox’ Methoden (s.u.) eine bessere und reliablere Alternative.</p>
<p>Auch für einfaktorielle ANOVAs hat Rand <span class="citation">Wilcox (<a href="#ref-Wilcox.2017" role="doc-biblioref">2017</a>)</span> natürlich wieder ein robustes Verfahren entwickelt und im Paket <code>WRS2</code> <span class="citation">(Mair &amp; Wilcox, <a href="#ref-Mair.2020" role="doc-biblioref">2020</a>)</span> implementiert. Die entsprechende Funktion ist für einfaktorielle Varianzanalysen <code>t1way()</code>.</p>
<pre class="r"><code>library(WRS2)

t1way(joy ~ backpack, data = phantasialand)</code></pre>
<pre><code>## Call:
## t1way(formula = joy ~ backpack, data = phantasialand)
## 
## Test statistic: F = 91.2352 
## Degrees of freedom 1: 3 
## Degrees of freedom 2: 55.94 
## p-value: 0 
## 
## Explanatory measure of effect size: 0.92</code></pre>
<p>Wir erhalten ein signifikantes Ergebnis (<span class="math inline">\(F_t(3, 55.94)= 91.24, p &lt; .001, \xi = .91\)</span>), was uns auch hier wieder sagt, dass sich die Gruppenmittelwerte unterscheiden. Robuste Post-hoc-Tests gibt es natürlich auch wieder; bei einfaktoriellen Varianzanalysen nutzt man die Funktion <code>lincon()</code>.</p>
<pre class="r"><code>lincon(joy ~ backpack, data = phantasialand)</code></pre>
<pre><code>## Call:
## lincon(formula = joy ~ backpack, data = phantasialand)
## 
##                     psihat ci.lower ci.upper p.value
## None vs. Light     2.36830  1.55112  3.18548 0.00000
## None vs. Heavy     2.77828  1.87293  3.68364 0.00000
## None vs. Handcart  6.64103  5.53054  7.75151 0.00000
## Light vs. Heavy    0.40998 -0.44968  1.26964 0.20021
## Light vs. Handcart 4.27273  3.19526  5.35019 0.00000
## Heavy vs. Handcart 3.86275  2.72189  5.00360 0.00000</code></pre>
<p>Auch hier sind die Ergebnisse wieder identisch mit der normalen ANOVA. Es besteht zwischen allen Gruppen ein signifikanter Unterschied, außer zwischen den Besuchern mit leichtem oder schwerem Rucksack.</p>
</div>
<div id="non-parametrisch" class="section level2">
<h2>Non-parametrisch</h2>
<p>Immer noch gelehrt, aber nicht mehr zur Anwendung gedacht, sind non-parametrische Verfahren, also jene, die keine Annahme bezüglich einer Normalverteilung haben. Ihre Anwendungsgebiete sind eng beschränkt und deshalb sollte man immer <a href="#robust">robuste Verfahren</a> verwenden. Wer es dennoch falsch machen und sich in vorherige Statistik-Jahzente begeben möchte, der weicht bei einfaktoriellen Varianzanalysen mit kleinen Stichprobengrößen und Abweichungen von der Normalverteilung auf den Kruskal-Wallis-Test <span class="citation">(Kruskal &amp; Wallis, <a href="#ref-Kruskal.1952" role="doc-biblioref">1952</a>)</span> aus.</p>
<pre class="r"><code># Kruskal-Wallis-Test
phantasialand %&gt;% 
  kruskal_test(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 1 x 6
##   .y.       n statistic    df        p method        
## * &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;         
## 1 joy     186      116.     3 6.80e-25 Kruskal-Wallis</code></pre>
<pre class="r"><code># Effektstärke
phantasialand %&gt;% 
  kruskal_effsize(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 1 x 5
##   .y.       n effsize method  magnitude
## * &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 joy     186   0.619 eta2[H] large</code></pre>
<p>Der Kruskal-Wallis-Test ist signifikant (<span class="math inline">\(H(3)=116, p &lt; .001, \eta^2[H] = .62\)</span>) und zeigt uns so einen signifikanten Unterschied der Mittelwerte an. Üblicherweise nutzt man als Post-hoc-Test nach einem signifikanten Kruskal-Wallis-Test die Methode nach Dunn <span class="citation">(Dunn, <a href="#ref-Dunn.1964" role="doc-biblioref">1964</a>)</span>.</p>
<pre class="r"><code>phantasialand %&gt;% 
  dunn_test(joy ~ backpack)</code></pre>
<pre><code>## # A tibble: 6 x 9
##   .y.   group1 group2      n1    n2 statistic        p    p.adj p.adj.signif
## * &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
## 1 joy   None   Light       42    53     -4.54 5.67e- 6 1.13e- 5 ****        
## 2 joy   None   Heavy       42    56     -5.83 5.69e- 9 2.27e- 8 ****        
## 3 joy   None   Handcart    42    35    -10.7  1.44e-26 8.63e-26 ****        
## 4 joy   Light  Heavy       53    56     -1.31 1.89e- 1 1.89e- 1 ns          
## 5 joy   Light  Handcart    53    35     -6.91 5.01e-12 2.50e-11 ****        
## 6 joy   Heavy  Handcart    56    35     -5.81 6.17e- 9 2.27e- 8 ****</code></pre>
<p>Nach dem Dunn-Test finden wir einen signifikanten Unterschied zwischen allen Gruppen, außer zwischen jenen Besuchern mit leichtem und schwerem Rucksack.</p>
</div>
</div>
<div id="aus-der-praxis" class="section level1">
<h1>Aus der Praxis</h1>
<p><span class="citation">Gallup et al. (<a href="#ref-Gallup.2003" role="doc-biblioref">2003</a>)</span> hatten sehr viel Spaß im Labor als sie untersuchten, ob die Penisform einen evolutionären Vorteil mit sich bringt. Genauer gesagt haben sie sich die Frage gestellt, ob die Form der Eichel als “Sperma-Schieber” funktionieren könnte. Mit einer Eichel, die eine ausgeprägte “Kante” hat, könnte Mann B während des Geschlechtsverkehrs die Hinterlassenschaften von Mann A “rauskratzen” und so relativ mehr von seinem eigenen Sperma zurücklassen. Dafür haben sie sich das Modell einer Vagina und drei Dildos besorgt. In das Vagina-Modell füllten sie künstliches Sperma und penetrierten diese dann mit den drei Dildos. Anschließend haben sie gemessen, wie viel Sperma der Dildo “rausgeschabt” hat. Was man so alles publizieren kann. Die Daten zu ihrer Versuchsreihe finden sich in der Datei <code>gallup.sav</code> und stammen von der <a href="https://edge.sagepub.com/field5e">begleitenden Website</a> von <span class="citation">Field (<a href="#ref-Field.2018" role="doc-biblioref">2018</a>)</span>. der Datensatz umfasst zwei Variablen, einmal die Form des Phallus (<code>phallus</code>) mit drei Faktorstufen (“No Coronal Ridge” = keine Eichel-Kante, “Minimal Corona Ridge” = kleine Kante, “Coronal Ridge” = normale Kante) und die Menge an “rausgeschabtem” Sperma (<code>displace</code>).</p>
<div id="klassisch-1" class="section level2">
<h2>Klassisch</h2>
<div id="eda-1" class="section level3">
<h3>EDA</h3>
<pre class="r"><code>penis &lt;- read_spss(&quot;data/gallup.sav&quot;) %&gt;% janitor::clean_names()

penis &lt;- penis %&gt;% mutate_if(is.labelled, as_factor)

penis</code></pre>
<pre><code>## # A tibble: 15 x 2
##    phallus               displace
##    &lt;fct&gt;                    &lt;dbl&gt;
##  1 No Coronal Ridge          21.5
##  2 No Coronal Ridge          35.8
##  3 No Coronal Ridge          61.7
##  4 No Coronal Ridge          22.0
##  5 No Coronal Ridge          35.5
##  6 Minimal Coronal Ridge     93.1
##  7 Minimal Coronal Ridge     80.8
##  8 Minimal Coronal Ridge     91.1
##  9 Minimal Coronal Ridge     97.4
## 10 Minimal Coronal Ridge     93.2
## 11 Coronal Ridge             99.2
## 12 Coronal Ridge             79.7
## 13 Coronal Ridge             91.0
## 14 Coronal Ridge             99.2
## 15 Coronal Ridge             86.9</code></pre>
<p>Wir haben insgesamt 15 Beobachtungen und 5 pro Faktorstufe.</p>
<pre class="r"><code>penis %&gt;%
  group_by(phallus) %&gt;% 
  get_summary_stats()</code></pre>
<pre><code>## # A tibble: 3 x 14
##   phallus variable     n   min   max median    q1    q3   iqr   mad  mean    sd
##   &lt;fct&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 No Cor~ displace     5  21.5  61.7   35.5  22.0  35.8 13.8  20.0   35.3 16.3 
## 2 Minima~ displace     5  80.8  97.4   93.1  91.1  93.2  2.11  3.06  91.1  6.23
## 3 Corona~ displace     5  79.7  99.2   91.0  86.9  99.2 12.3  12.2   91.2  8.35
## # ... with 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<p>Aufgrund der deskriptiven Statistiken könnten wir vermuten, dass die Form des Phallus tatsächlich einen Einfluss darauf hat, wie viel Sperma aus der Vagina entfernt werden kann. Ein Dildo ohne Eichel-Kante entfernt im Mittel <span class="math inline">\(M = 35.3, SD = 16.3\)</span> Prozent des enthaltenen Spermas. Die beiden anderen Dildos schaffen beide über 90%. Der Unterschied wird vor allem in der Abbildung schön deutlich.</p>
<p><img src="einfaktorielle-anova_files/figure-html/unnamed-chunk-18-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Da wir relativ wening Datenpunkte haben, sollten wir die Voraussetzungen prüfen.</p>
<pre class="r"><code># Shapiro-Wilk-Test
penis %&gt;% 
  group_by(phallus) %&gt;% 
  shapiro_test(displace)</code></pre>
<pre><code>## # A tibble: 3 x 4
##   phallus               variable statistic     p
##   &lt;fct&gt;                 &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 No Coronal Ridge      displace     0.849 0.190
## 2 Minimal Coronal Ridge displace     0.865 0.246
## 3 Coronal Ridge         displace     0.911 0.472</code></pre>
<pre class="r"><code># Levene-Test
penis %&gt;% 
  levene_test(displace ~ phallus)</code></pre>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic     p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1     2    12      1.15 0.349</code></pre>
</div>
<div id="durchführung-1" class="section level3">
<h3>Durchführung</h3>
<p>Beide Tests fallen nicht signifikant aus, was für uns gut ist, da wir die ANOVA nun rechnen dürfen.</p>
<pre class="r"><code>penis %&gt;% 
  anova_test(displace ~ phallus)</code></pre>
<pre><code>## ANOVA Table (type II tests)
## 
##    Effect DFn DFd      F        p p&lt;.05   ges
## 1 phallus   2  12 41.559 4.03e-06     * 0.874</code></pre>
<p><span class="math inline">\(p &lt; .05\)</span> und so können wir festhalten, dass sich die Mittelwerte irgendwo signifikant voneinander unterscheiden. Da wir eine Hypothese darüber haben, welche Gruppen besonders viel oder wenig Sperma entfernen, können wir geplante Kontraste berechnen. Wir vermuten, dass der Dildo ohne Eichel-Kante weniger Sperma entfernt als die Dildos mit Kante. Des Weiteren könnten wir vermuten, dass der Dildo mit normaler Kante mehr Sperma entfernt als der Dildo mit kleiner Kante. Da wir <span class="math inline">\(k = 3\)</span> Gruppen haben, müssen wir <span class="math inline">\(3-1 = 2\)</span> Kontraste <a href="kontraste.html">entsprechend unserer bekannten Regeln</a> definieren.</p>
<table>
<thead>
<tr class="header">
<th>Gruppe</th>
<th>Kontrast 1</th>
<th>Kontrast 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Ridge</td>
<td>-2</td>
<td>0</td>
</tr>
<tr class="even">
<td>Minimal Ridge</td>
<td>1</td>
<td>-1</td>
</tr>
<tr class="odd">
<td>Normal Ridge</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Summe</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Zu Beginn vergewissern wir uns noch einmal, dass unsere Faktorstufen auch in der gewünschten Reihenfolge sind.</p>
<pre class="r"><code>penis %&gt;% 
  pull(phallus) %&gt;% 
  levels()</code></pre>
<pre><code>## [1] &quot;No Coronal Ridge&quot;      &quot;Minimal Coronal Ridge&quot; &quot;Coronal Ridge&quot;</code></pre>
<p>Das sieht gut aus, die Reihenfolge der Faktorstufen ist wie in der Tabelle. Wir können nun unsere gewichte vergeben.</p>
<pre class="r"><code>contrast_1 &lt;- c(-2, 1, 1)
contrast_2 &lt;- c(0, -1, 1)

my_contrasts &lt;- cbind(contrast_1, contrast_2)

contrasts(penis$phallus) &lt;- my_contrasts

penis %&gt;% 
  pull(phallus) %&gt;% 
  contrasts()</code></pre>
<pre><code>##                       contrast_1 contrast_2
## No Coronal Ridge              -2          0
## Minimal Coronal Ridge          1         -1
## Coronal Ridge                  1          1</code></pre>
<p>Unsere Kontraste sind nun ordentlich hinterlegt und wir können die Analyse durchführen.</p>
<pre class="r"><code>penis_results &lt;- aov(displace ~ phallus, data = penis)

summary.lm(penis_results)</code></pre>
<pre><code>## 
## Call:
## aov(formula = displace ~ phallus, data = penis)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.8276  -7.3288   0.1826   4.1917  26.4298 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       72.54891    2.88784  25.122 9.60e-12 ***
## phalluscontrast_1 18.61686    2.04201   9.117 9.63e-07 ***
## phalluscontrast_2  0.05679    3.53686   0.016    0.987    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.18 on 12 degrees of freedom
## Multiple R-squared:  0.8738, Adjusted R-squared:  0.8528 
## F-statistic: 41.56 on 2 and 12 DF,  p-value: 4.032e-06</code></pre>
<p>Unsere Kontraste bestätigen, was wir uns anhand der Abbildung vielleicht schon gedacht haben. Es gibt im Hinblick auf die Menge des entfernten Spermas einen signifikanten Unterschied zwischen dem Dildo ohne Eichel-Kante und jenen mit einer solchen Kante. Darüber hinaus unterscheiden sich die beiden Dildos mit Eichel-Kante nicht voneinander; beide entfernten ähnlich viel Sperma aus der Modell-Vagina. Die Effektstärke können wir berechnen als <span class="math display">\[r_\text{Kontrast} = \sqrt{\dfrac{t^2}{t^2 + df}}\]</span></p>
<p>Alternativ hätten wir Post-hoc-Tests berechnen können, mit denen wir auf das identische Ergebnis gekommen wären.</p>
<pre class="r"><code>penis %&gt;% 
  tukey_hsd(displace ~ phallus)</code></pre>
<pre><code>## # A tibble: 3 x 8
##   term   group1      group2     estimate conf.low conf.high   p.adj p.adj.signif
## * &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;       
## 1 phall~ No Coronal~ Minimal C~   55.8       36.9      74.7 1.21e-5 ****        
## 2 phall~ No Coronal~ Coronal R~   55.9       37.0      74.8 1.18e-5 ****        
## 3 phall~ Minimal Co~ Coronal R~    0.114    -18.8      19.0 1.00e+0 ns</code></pre>
</div>
<div id="berichten-1" class="section level3">
<h3>Berichten</h3>
<p>We found the shape of the phallus to have a significant influence on the amount of displaced sperm, <span class="math inline">\(F(2,12) = 41.56, p &lt; .001, \eta_G^2 = .874\)</span>. A priori defined contrasts revealed a significant difference between phalli with a coronal ridge and those without, <span class="math inline">\(t(12) = 9.12, p &lt; .001, r_\text{contrast} = 0.93\)</span>. If there was a coronal ridge, its size didn’t affect the amount of displaced sperm, <span class="math inline">\(t(12)=0.02, p = .987, r_\text{contrast} = .005\)</span>.</p>
</div>
</div>
<div id="robust-1" class="section level2">
<h2>Robust</h2>
<p>Wären die Voraussetzungen an eine einfaktorielle Varianzanalyse nicht gegeben, z.B. durch kleine Stichprobengröße, gepaart mit signifikanten Shapiro-Wilk-Tests, dann könnten wir auch die vorgestellten robusten Verfahren von <span class="citation">Wilcox (<a href="#ref-Wilcox.2017" role="doc-biblioref">2017</a>)</span> verwenden.</p>
<pre class="r"><code># Der Test an sich
t1way(displace ~ phallus, data = penis)</code></pre>
<pre><code>## Call:
## t1way(formula = displace ~ phallus, data = penis)
## 
## Test statistic: F = 39.5672 
## Degrees of freedom 1: 2 
## Degrees of freedom 2: 2.81 
## p-value: 0.00872 
## 
## Explanatory measure of effect size: 0.91</code></pre>
<pre class="r"><code># Post-hoc-Tests
lincon(displace ~ phallus, data = penis)</code></pre>
<pre><code>## Call:
## lincon(formula = displace ~ phallus, data = penis)
## 
##                                               psihat  ci.lower  ci.upper
## No Coronal Ridge vs. Minimal Coronal Ridge -61.33214 -99.06445 -23.59983
## No Coronal Ridge vs. Coronal Ridge         -61.26282 -91.61190 -30.91375
## Minimal Coronal Ridge vs. Coronal Ridge      0.06931 -30.82820  30.96683
##                                            p.value
## No Coronal Ridge vs. Minimal Coronal Ridge 0.01728
## No Coronal Ridge vs. Coronal Ridge         0.00528
## Minimal Coronal Ridge vs. Coronal Ridge    0.99045</code></pre>
<p>Mit den robusten Tests würden wir auf dasselbe Ergebnis kommen: Es gibt einen signifikanten Unterschied zwischen den Dildos in Bezug auf die durchschnittliche Menge des entfernten Spermas, <span class="math inline">\(F_t(2, 2.81) = 39.57, p = .009, \xi = .91\)</span>. Die Post-hoc-Tests zeigen, dass sich beide Dildos mit Eichel-Kante vom Dildo ohne Kante unterscheiden.</p>
</div>
<div id="non-parametrisch-1" class="section level2">
<h2>Non-parametrisch</h2>
<p>Wie immer rate ich davon ab, non-parametrische Tests zu berechnen, da die robusten Verfahren generell besser und breiter in ihrer Anwendung sind. Der Kruskal-Wallis-Test würde jedoch so durchgeführt.</p>
<pre class="r"><code># Kruskal-Wallis-Test
penis %&gt;% 
  kruskal_test(displace ~ phallus)</code></pre>
<pre><code>## # A tibble: 1 x 6
##   .y.          n statistic    df       p method        
## * &lt;chr&gt;    &lt;int&gt;     &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;         
## 1 displace    15      9.38     2 0.00919 Kruskal-Wallis</code></pre>
<pre class="r"><code># Effektstärke
penis %&gt;% 
  kruskal_effsize(displace ~ phallus)</code></pre>
<pre><code>## # A tibble: 1 x 5
##   .y.          n effsize method  magnitude
## * &lt;chr&gt;    &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 displace    15   0.615 eta2[H] large</code></pre>
<pre class="r"><code># Post-hoc-Tests nach Dunn
penis %&gt;% 
  dunn_test(displace ~ phallus)</code></pre>
<pre><code>## # A tibble: 3 x 9
##   .y.    group1     group2        n1    n2 statistic       p  p.adj p.adj.signif
## * &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;      &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;       
## 1 displ~ No Corona~ Minimal C~     5     5    2.69   0.00721 0.0216 *           
## 2 displ~ No Corona~ Coronal R~     5     5    2.62   0.00889 0.0216 *           
## 3 displ~ Minimal C~ Coronal R~     5     5   -0.0707 0.944   0.944  ns</code></pre>
<p>Auch der Kruskal-Wallis-Test kommt zu dem Ergebnis, dass sich die Mittelwerte signifikant voneinander unterscheiden, <span class="math inline">\(H(2) = 9.38, p = .009, \eta^2[H] = .62\)</span>. Die Post-hoc-Tests nach Dunn zeigten ebenfalls einen signifikanten Unterschied zwischen den Dildos mit Eichel-Kante und jenem ohne.</p>
</div>
</div>
<div id="literatur" class="section level1 unnumbered">
<h1>Literatur</h1>
<div id="refs" class="references">
<div id="ref-Dunn.1964">
<p>Dunn, O. J. (1964). Multiple Comparisons Using Rank Sums. <em>Technometrics</em>, <em>6</em>(3), 241–252. <a href="https://doi.org/10.1080/00401706.1964.10490181">https://doi.org/10.1080/00401706.1964.10490181</a></p>
</div>
<div id="ref-Field.2018">
<p>Field, A. P. (2018). <em>Discovering Statistics using IBM SPSS Statistics</em> (5th ed.). SAGE.</p>
</div>
<div id="ref-Gallup.2003">
<p>Gallup, G., Burch, R. L., Zappieri, M. L., Parvez, R. A., Stockwell, M. L., &amp; Davis, J. A. (2003). The human penis as a semen displacement device. <em>Evolution and Human Behavior</em>, <em>24</em>(4), 277–289. <a href="https://doi.org/10.1016/S1090-5138(03)00016-3">https://doi.org/10.1016/S1090-5138(03)00016-3</a></p>
</div>
<div id="ref-Kruskal.1952">
<p>Kruskal, W. H., &amp; Wallis, W. A. (1952). Use of Ranks in One-Criterion Variance Analysis. <em>Journal of the American Statistical Association</em>, <em>47</em>(260), 583–621. <a href="https://doi.org/10.1080/01621459.1952.10483441">https://doi.org/10.1080/01621459.1952.10483441</a></p>
</div>
<div id="ref-Mair.2020">
<p>Mair, P., &amp; Wilcox, R. R. (2020). Robust statistical methods in R using the WRS2 package. <em>Behavior Research Methods</em>, <em>52</em>(2), 464–488. <a href="https://doi.org/10.3758/s13428-019-01246-w">https://doi.org/10.3758/s13428-019-01246-w</a></p>
</div>
<div id="ref-Toothaker.1993">
<p>Toothaker, L. E. (1993). <em>Multiple Comparison Procedures</em>. SAGE.</p>
</div>
<div id="ref-Wilcox.2017">
<p>Wilcox, R. R. (2017). <em>Introduction to Robust Estimation and Hypothesis Testing</em> (4th ed.). Elsevier Academic Press.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
