<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Faktorielle ANOVA</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="images/broom.ico">

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Chamber of Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Allgemeines
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="software.html">Software</a>
    </li>
    <li>
      <a href="r-basics.html">R Basics</a>
    </li>
    <li>
      <a href="stil.html">Stil</a>
    </li>
    <li>
      <a href="pakete.html">Pakete</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mittelwerte vergleichen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mittelwerte-vergleichen.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">t-Tests</li>
    <li>
      <a href="t-test-einstichprobe.html">Bei einer Stichprobe</a>
    </li>
    <li>
      <a href="t-test-unabhaengig.html">Bei unabhängigen Stichproben</a>
    </li>
    <li>
      <a href="t-test-abhaengig.html">Bei abhängigen Stichproben</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ANOVAs</li>
    <li>
      <a href="einfaktorielle-anova.html">Einfaktorielle ANOVA</a>
    </li>
    <li>
      <a href="faktorielle-anova.html">Faktorielle ANOVA</a>
    </li>
    <li class="dropdown-header">ANCOVA</li>
    <li class="dropdown-header">Repeated Measures ANOVA</li>
    <li class="dropdown-header">Mixed ANOVA</li>
    <li>
      <a href="kontraste.html">Geplante Kontraste</a>
    </li>
    <li>
      <a href="post-hoc-tests.html">Post-hoc-Tests</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-question"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="voraussetzungen.html">Voraussetzungen im GLM</a>
    </li>
    <li>
      <a href="zentraler-grenzwertsatz.html">Zentraler Grenzwertsatz</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Faktorielle ANOVA</h1>

</div>


<p><img src="images/ice-cream_r.jpg" /></p>
<p>Mit einer (allgemeinen) faktoriellen ANOVA kann man mehr als zwei Gruppenmittelwerte in Abhängigkeit von kategorialen Prädiktoren vergleichen. Da die ANOVA ein Omnibus-Test ist, und so nur anzeigt, ob irgendwo ein signifikanter Unterschied zwischen den betrachteten Mittelwerten besteht, nutzt man entweder Kontraste oder Post-hoc-Tests, um herauszufinden, welche Mittelwerte sich letztendlich signifikant voneinander unterscheiden. Zusätzlich kann eine <em>Simple Effects Analysis</em> dazu genutzt werden, Unterschiede auf einzelnen Faktorstufen festzustellen.</p>
<div id="pakete" class="section level1">
<h1>Pakete</h1>
<p>Alle Berechnungen und Abbildungen können wir mit unseren <a href="pakete.html">Standardpaketen</a> durchführen. Wir benötigen das <code>tidyverse</code> zum Data Wrangling und zur Visualisierung der Daten. <code>haven</code> benötigen wir für den Import von SPSS-Dateien und <code>rstatix</code> für statistische Analysen.</p>
<pre class="r"><code>library(tidyverse)
library(haven)
library(rstatix)</code></pre>
</div>
<div id="beispiel" class="section level1">
<h1>Beispiel</h1>
<p>Jeder liebt es, so viel ist klar. Aber mögen alle Personen jede Sorte Eis gleich gerne? Pfiffige Forscher haben sich an einem schönen Sommertag an einer Eisdile in der Dortmunder Innenstadt platziert und viele zufällig vorbeikommende Passanten vier Eissorten kosten lassen. Die Probanden konnten dann auf einer Skala von 0 – 20 angeben, wie lecker sie die eben probierte Eissorte fanden. Ein höherer Wert bedeutet eine bessere Bewertung. Wir wollen herausfinden, ob die Sorte selbst und das Geschlecht des Verkosters einen Einfluss auf den Geschmack hat. Wichtig ist dabei zu bachten, dass jeder Passant nur <em>eine</em> Eissorte probiert hat.</p>
<div id="klassisch" class="section level2">
<h2>Klassisch</h2>
<p>Die Daten zu diesem Experiment sind in der Datei <code>ice_cream.sav</code>. In der ersten Spalte (<code>flavor</code>) ist der Geschmack eingetragen, in der zweiten Spalte (<code>sex</code>) das Geschlecht des Verkosters. In der dritten Spalte finden wir unsere abhängige Variable <code>yumminess</code>. Wir berechnen hier also eine 4 <span class="math inline">\(\times\)</span> 2 faktorielle ANOVA mit den Zwischensubjektfaktoren “Eissorte” mit vier Fakorstufen (“Vanilla”, “Chocolate”, “Cookie” und “Champagne”) und “Geschlecht” mit zwei Faktorstufen (“Female” und “Male”).</p>
<pre class="r"><code>ice_cream &lt;- read_spss(&quot;data/ice_cream.sav&quot;)

ice_cream &lt;- ice_cream %&gt;% mutate_if(is.labelled, as_factor)

ice_cream</code></pre>
<pre><code>## # A tibble: 295 x 4
##    id    flavor    sex    yumminess
##    &lt;chr&gt; &lt;fct&gt;     &lt;fct&gt;      &lt;dbl&gt;
##  1 1     Champagne Female        14
##  2 2     Vanilla   Female        19
##  3 3     Champagne Female        16
##  4 4     Chocolate Female        17
##  5 5     Chocolate Female        16
##  6 6     Vanilla   Male          16
##  7 7     Vanilla   Female        17
##  8 8     Vanilla   Male          18
##  9 9     Cookie    Male          13
## 10 10    Champagne Female        13
## # ... with 285 more rows</code></pre>
<div id="voraussetzungen" class="section level3">
<h3>Voraussetzungen</h3>
<p>Da wir uns im GLM bewegen, gelten die üblichen <a href="voraussetzungen.html">Voraussetzungen</a>.</p>
</div>
<div id="eda" class="section level3">
<h3>EDA</h3>
<pre class="r"><code># Deskriptive Statistiken zur Eissorte...
ice_cream %&gt;%
  group_by(flavor) %&gt;% 
  get_summary_stats()</code></pre>
<pre><code>## # A tibble: 4 x 14
##   flavor variable     n   min   max median    q1    q3   iqr   mad  mean    sd
##   &lt;fct&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Vanil~ yummine~    74    11    20   17    15      18  3     2.96  16.6  2.18
## 2 Choco~ yummine~    81    12    20   17    16      18  2     1.48  17.2  1.68
## 3 Cookie yummine~    80     8    20   14.5  12.8    17  4.25  3.71  14.6  2.83
## 4 Champ~ yummine~    60     2    20   14    11      15  4     2.96  13.2  3.64
## # ... with 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<pre class="r"><code># ...zur Verteilung der Geschlechter...
ice_cream %&gt;%
  group_by(sex) %&gt;% 
  get_summary_stats()</code></pre>
<pre><code>## # A tibble: 2 x 14
##   sex   variable     n   min   max median    q1    q3   iqr   mad  mean    sd
##   &lt;fct&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Fema~ yummine~   162    10    20     17    15    18     3  2.96  16.4  2.21
## 2 Male  yummine~   133     2    20     15    12    17     5  4.45  14.5  3.51
## # ... with 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<pre class="r"><code># ...und zu den Eissorten für jedes Geschlecht
ice_cream %&gt;%
  group_by(flavor, sex) %&gt;% 
  get_summary_stats()</code></pre>
<pre><code>## # A tibble: 8 x 15
##   flavor sex   variable     n   min   max median    q1    q3   iqr   mad  mean
##   &lt;fct&gt;  &lt;fct&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Vanil~ Fema~ yummine~    36    12    20     17 16       19  3     2.22  17.1
## 2 Vanil~ Male  yummine~    38    11    20     16 15       18  3     2.22  16.1
## 3 Choco~ Fema~ yummine~    41    13    20     17 16       18  2     1.48  17.2
## 4 Choco~ Male  yummine~    40    12    20     17 16       18  2     1.48  17.1
## 5 Cookie Fema~ yummine~    45    10    20     16 14       18  4     2.96  16.1
## 6 Cookie Male  yummine~    35     8    18     13 11.5     14  2.5   1.48  12.8
## 7 Champ~ Fema~ yummine~    40    11    20     15 14       17  3     1.48  15.2
## 8 Champ~ Male  yummine~    20     2    13     10  8.75    11  2.25  1.48   9.2
## # ... with 3 more variables: sd &lt;dbl&gt;, se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<p>Wir haben Daten zu vier Eissorten. Verköstigt wurden am häufigsten Schokolade (<span class="math inline">\(n = 81\)</span>) und Cookie (<span class="math inline">\(n = 80\)</span>); bewertet wurden am besten Vanille (<span class="math inline">\(M = 16.57, SD = 2.18\)</span>) und Schokolade (<span class="math inline">\(M = 17.16, SD = 1.68\)</span>). Insgesamt haben <span class="math inline">\(N = 295\)</span> Passanten an der Untersuchung teilgenommen, wovon <span class="math inline">\(n = 162\)</span> Frauen und <span class="math inline">\(n = 133\)</span> Männer waren.</p>
<p><img src="faktorielle-anova_files/figure-html/unnamed-chunk-6-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Aufgrund der Abbildung bekommen wir eine grobe Idee davon, dass die untersuchten Frauen alle Eissorten in etwa gleich lecker fanden. Die Männer jedoch stehen weniger auf Cookie und überhaupt nicht auf Champagner. (Bah!) Jetzt ist die Frage, ob unsere Einschätzung, dass sich die Mittelwerte tatsächlich signifikant unterscheiden, richtig ist. Dafür berechnen wir die ANOVA.</p>
</div>
<div id="durchführung" class="section level3">
<h3>Durchführung</h3>
<p>Auch hier haben wir, wie bei der <a href="einfaktorielle-anova.html">einfaktoriellen ANOVA</a>, zwei Möglichkeiten, die Funktionsargumente einzugeben. Einmal als Formelschreibweise und einmal als Explizite Nennung in Form der Funktionsargumente. <a href="https://github.com/kassambara/rstatix/issues/40">Momentan sind die Ergebnisse für die Definition in Formelschreibweise falsch (CRAN-Version 0.5.0)</a>, deshalb sollte man die Faktoren explizit als Funktionsargumente angeben. Wichtig ist hierbei, dass das Funktionsargument <code>type = 3</code> angegeben wird. In der Psychologie (und generell in den Sozialwissenschaften und der Medizin) werden standardmäßig <a href="http://md.psych.bio.uni-goettingen.de/mv/unit/lm_cat/lm_cat_unbal_ss_explained.html">Quadratsummen vom Typ “III”</a> berechnet.</p>
<pre class="r"><code># Formelschreibweise
ice_cream %&gt;% 
  anova_test(yumminess ~ flavor*sex, type = 3)

# Funktionsargumente
ice_cream %&gt;% 
  anova_test(dv = yumminess, between = c(flavor, sex), type = 3)</code></pre>
<p>Dieses Vorgehen liefert uns folgendes Resultat.</p>
<pre class="r"><code>ice_cream %&gt;% 
  anova_test(dv = yumminess, between = c(flavor, sex), type = 3)</code></pre>
<pre><code>## ANOVA Table (type III tests)
## 
##       Effect DFn DFd       F        p p&lt;.05   ges
## 1     flavor   3 287  73.263 3.28e-35     * 0.434
## 2        sex   1 287 106.711 1.78e-21     * 0.271
## 3 flavor:sex   3 287  25.377 1.37e-14     * 0.210</code></pre>
<p>An dieser Stelle lohnt es sich etwas, auf die Interpretation der Ergebnisse einzugehen. In den Zeilen <code>flavor</code> und <code>sex</code> sind die Haupteffekte dieser beiden Faktoren zu finden. Hat der Faktor “flavor” (= Eissorte) allein einen Einfluss auf die Einschätzung der Probanden? Ja, der Haupteffekt für “flavor” ist signifikant, da <span class="math inline">\(p &lt; .05\)</span>. Das gleiche gilt für den Haupteffekt, und somit Einfluss, von “sex” (= Geschlecht); auch hier ist <span class="math inline">\(p &lt; .05\)</span>. In der dritten Zeile finden wir den <strong>Interaktionseffekt</strong> von “flavor” und “sex”. Mit diesem wird also angegeben, ob es zwischen den beiden Faktoren eine Interaktion gibt. Eine Interaktion würde bedeuten, dass der Faktor “flavor” die abhängige Variable “yumminess” nicht in allen Faktorstufen von “sex” gleich beeinflusst. Der Einfluss von “flavor” auf “yumminess” wäre also zwischen den Geschlechtern unterschiedlich. Man kann das natrülich auch andersrum sagen: Der Interaktionseffekt gibt an, ob der Einfluss des Faktors “sex” auf “yumminess” in allen Faktorstufen von “flavor” gleich ist. Hier ist der ebenfalls signifikant, da <span class="math inline">\(p &lt; .05\)</span>.</p>
<p>Bei diesem Versuch einer Beschreibung des Interaktionseffekts kann einem der Kopf rauchen. Deshalb ist es immer sinnvoll, sich die Daten in Diagrammen anzuschauen. Unten findest du die Daten auf zwei unterschiedliche Weisen präsentiert: Einmal ist “flavor” auf der <span class="math inline">\(x\)</span>-Achse und die Linien sind getrennt nach “sex” (A; diese Abbildung sollte Dir bekannt vorkommen, weil sie identisch mit der oberen ist). Das andere Mal ist “sex” auf der <span class="math inline">\(x\)</span>-Achse und die Linien sind nach “flavor” getrennt (B).</p>
<p><img src="faktorielle-anova_files/figure-html/unnamed-chunk-9-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Diese Abbildungen zeigen beide denselben Sachverhalt, nur “von einer anderen Seite”. Welche Seite man darstellen sollte, hängt von verschiedenen Faktoren ab. Einerseits natürlich von der untersuchten Fragestellung. In diesem Fall wollten wir untersuchen, ob sich die “yumminess” von Eissorten unterscheidet, also haben wir die Eissorten auf die <span class="math inline">\(x\)</span>-Achse gepackt. Zusätzlich dazu interessierte uns der Einfluss des Geschlechts, anhand dessen wir dann die Linien getrennt haben. Hätten wir uns jedoch eher gefragt, ob sich Frauen oder Männer generell in ihrer Einschätzung der Eissorten-“yumminess” unterscheiden, hätten wir wahrscheinlich “sex” auf die <span class="math inline">\(x\)</span>-Achse schmeißen können, genau wie in Abbildung B.</p>
<p>Andererseits ist es wichtig auf dem Schirm zu haben, was das menschliche Gehirn noch verstehen und analysieren kann. Wir sind zwar mit einer großen rechenleistung ausgestattet, aber Bilder vermögen uns doch auch zu täuschen oder zu verwirren. Genrell kann man sagen, <strong>dass ein Interaktionseffekt vorliegt, wenn die eingezeichneten Linien nicht parallel verlaufen</strong>. Aus welcher Abbildung das besser hervorgeht, sollte man immer im Einzelfall entscheiden.</p>
<p>Wir haben jetzt also geklärt, dass ein Interaktionseffekt vorliegt. Nun sind beide Haupteffekte signifikant und der Interaktionseffekt noch dazu. Was bedeutet das jetzt? Irgendwie haben also die Eissorte und das Geschlecht der Passanten (“flavor” und “sex”) einen Einfluss auf die “yumminess” (als Haupteffekte), aber dieser Einfluss variiert, je nach Geschmack oder Geschlecht (Interaktionseffekt)?! Im Prinzip kann man sagen: Jap, genau. Und an dieser Stelle wird deutlich, was viele falsch machen, denn <strong>die Interpretation von Haupteffekten bei einem signifikanten Interaktionseffekt ist sinnlos</strong>. Statistisch sind die Haupteffekte zwar signifikant (ignoriert man das Geschlecht, hat also die Eissorte im Mittel einen Einfluss auf die “yumminess” und ignoriert man die Eissorte, hat Geschlecht im Mittel einen Einfluss auf die “yumminess”), aber diese Effekte <em>variieren</em> ja gerade in Abhängigkeit von den jeweiligen Faktorstufen, was uns der signifikante Interaktionseffekt ja mitteilt. Bei einem signifikanten Interaktionseffekt konzentrieren wir uns also nur auf diesen.</p>
<p>Aus Abbildung A können wir entnehmen, dass Frauen alle Eissorten ungefähr gleich gut einschätzten, die “yumminess” lag im Durchschnitt immer über 15. Männer hingegen hatten deutlichere Präferenzen: Bei Vanielle und Schokolade hielten sie noch mit und schätzten diese beiden Sorten ähnlich wie die Frauen ein, aber bei Cookie und spätestens bei Champagner war das Spiel vorbei. Diese beiden Sorten wurden von den Männern deutlich schlechter eingeschätzt als von den Frauen. Gibt es eine Möglichkeit herauszufinden, bei welcher Faktorstufe von “falvor” sich Frauen und Männer signifikant unterscheiden? Ja, die <em>Simple Effects Analysis</em>.</p>
</div>
<div id="simple-effects-analysis" class="section level3">
<h3>Simple Effects Analysis</h3>
<p>Hier unterscheiden sich alle bekannten Statistik-Programme erheblich darin, ob diese Analyse überhaupt durchgeführt werden kann. Natürlich können wir das in R machen. JASP-Nutzer können diese Analyse ebenfalls ausfählen. SPSS-Nutzer müssen sich mit der Syntax auskennen und ihn dort von Hand eintragen, weil der Befehl nicht in den Dialogfeldern zu finden ist.</p>
<p>Bei der <em>Simple Effect Analysis</em> sollte beachtet werden, ob die Voraussetzung der Varianzhomogenität erfüllt ist. Einfach gesagt nehmen wir uns nämlich nun die Daten für jede einzelne Faktorstufe von “flavor”, berechnen eine ANOVA und untersuchen so, ob sich das Geschlecht für jede Faktorstufe unterscheidet. Ist die Voraussetzung der Varianzhomogenität gegeben, unterscheiden sich die Varianzen der Faktorstufen also nicht signifikant voneinander (= nicht signifikanter Levene-Test; wie in diesem Fall), dann sollten die Fehler des gesamten Modells einbezogen werden <span class="citation">(Bibby, <a href="#ref-Bibby.2010" role="doc-biblioref">2010</a>)</span>. Sind die Varianzen jedoch signifikant unterschiedlich, sollten getrennte ANOVAs pro Faktorstufe berechnet werden.</p>
<div id="varianzhomogenität-angenommen" class="section level4">
<h4>Varianzhomogenität angenommen</h4>
<p>Bei angenommener Varianzhomogenität sollen wir also die “Fehler des Gesamtmodells” berücksichtigen. Zu Beginn müssen wir somit unser Gesamtmodell definieren. Da wir uns im GLM, also im allgemeinen linearen Modell bewegen, ist unser Modell immer eine Form des linearen Modells, das in R mit <code>lm()</code> definiert wird. Mit der Formelschreibweise setzen wir das so um.</p>
<pre class="r"><code>main_model &lt;- lm(yumminess ~ flavor * sex, data = ice_cream)</code></pre>
<p>Nun gehen wir genau so vor wie beschrieben und berechnen für jede Faktorstufe von “flavor” ganz normale ANOVAs, geben als Fehlerterme jedoch die des Gesamtmodells (<code>main_model</code>) an. Wir untersuchen an dieser Stelle also den Einfluss von “sex” auf “yumminess” für alle Faktorstufen von “flavor”.</p>
<pre class="r"><code>ice_cream %&gt;% 
  group_by(flavor) %&gt;% 
  anova_test(yumminess ~ sex, error = main_model)</code></pre>
<pre><code>## # A tibble: 4 x 8
##   flavor    Effect   DFn   DFd       F        p `p&lt;.05`       ges
##   &lt;fct&gt;     &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;
## 1 Vanilla   sex        1   287   4.22  4.10e- 2 &quot;*&quot;     0.015    
## 2 Chocolate sex        1   287   0.023 8.81e- 1 &quot;&quot;      0.0000785
## 3 Cookie    sex        1   287  48.4   2.35e-11 &quot;*&quot;     0.144    
## 4 Champagne sex        1   287 110.    6.18e-22 &quot;*&quot;     0.276</code></pre>
<p>Damit erhalten wir eine Übersicht über alle vier durchgeführten ANOVAs, in denen der Einfluss von “sex” auf “yumminess” untersucht wurde. Die weiblichen und männlichen Verkoster unterschieden sich demnach in der Einschätzung der “yumminess” bei den Sorten Vanille, Cookie und Champagner.</p>
</div>
<div id="varianzhomogenität-nicht-angenommen" class="section level4">
<h4>Varianzhomogenität nicht angenommen</h4>
<p>Nehmen wir keine Varianzhomogenität an, berechnen wir wieder für die einzelnen Faktorstufen getrennte ANOVAs, verzichten jedoch auf die Angabe der Fehlerterme.</p>
<pre class="r"><code>ice_cream %&gt;% 
  group_by(flavor) %&gt;% 
  anova_test(yumminess ~ sex)</code></pre>
<pre><code>## # A tibble: 4 x 8
##   flavor    Effect   DFn   DFd      F        p `p&lt;.05`      ges
##   &lt;fct&gt;     &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
## 1 Vanilla   sex        1    72  4.1   4.70e- 2 &quot;*&quot;     0.054   
## 2 Chocolate sex        1    79  0.035 8.52e- 1 &quot;&quot;      0.000443
## 3 Cookie    sex        1    78 40.0   1.48e- 8 &quot;*&quot;     0.339   
## 4 Champagne sex        1    58 94.1   9.37e-14 &quot;*&quot;     0.619</code></pre>
</div>
<div id="effektstärke" class="section level4">
<h4>Effektstärke</h4>
<p>Auch für die <em>Simple Effects Analysis</em> lassen sich Effektstärken für die einzelnen Vergleiche berechnen. Diese ergeben sich, wenn innerhalb der Faktorstufen nur zwei Gruppen miteinander vergleichen werden, als <span class="math display">\[r = \sqrt{\dfrac{F(1, df_\text{d})}{F(1, df_\text{d}) + df_\text{d}}}\]</span> mit <span class="math inline">\(df_\text{d}\)</span> als Freiheitsgrade der Fehler.</p>
<p>In diesem Beispiel haben wir Varianzhomogenität angenommen, da der Levene-Test nicht signifikant war. Die Effektstärke zwischen Frauen und Männern für den Geschmack Vanille ist somit <span class="math display">\[r = \sqrt{\dfrac{4.22}{4.22 + 287}}\]</span> also 0.12. Für die übrigen Faktorstufen von “flavor” finden wir</p>
<table>
<thead>
<tr class="header">
<th>Faktorstufe</th>
<th><span class="math inline">\(r\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vanille</td>
<td>0.12</td>
</tr>
<tr class="even">
<td>Schokolade</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td>Cookie</td>
<td>0.41</td>
</tr>
<tr class="even">
<td>Champagner</td>
<td>0.61</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="berichten" class="section level3">
<h3>Berichten</h3>
</div>
</div>
<div id="robust" class="section level2">
<h2>Robust</h2>
<pre class="r"><code>library(WRS2)

# Robuste zweifaktorielle ANOVA
t2way(yumminess ~ flavor * sex, data = ice_cream)</code></pre>
<pre><code>## Call:
## t2way(formula = yumminess ~ flavor * sex, data = ice_cream)
## 
##               value p.value
## flavor     251.7609   0.001
## sex         86.2149   0.001
## flavor:sex  82.1532   0.001</code></pre>
<pre class="r"><code># Robuster Post-hoc-Test für eine zweifaktorielle ANOVA
mcp2atm(yumminess ~ flavor * sex, data = ice_cream)</code></pre>
<pre><code>## Call:
## mcp2atm(formula = yumminess ~ flavor * sex, data = ice_cream)
## 
##                psihat ci.lower ci.upper p-value
## flavor1      -0.25926 -0.88143  0.36291 0.24884
## flavor2      -0.22222 -0.89690  0.45246 0.36767
## flavor3       0.33333 -0.36461  1.03128 0.19534
## flavor4       0.03704 -0.26093  0.33500 0.72777
## flavor5       0.59259  0.23646  0.94873 0.00007
## flavor6       0.55556  0.10689  1.00422 0.00138
## sex1          0.88889  0.33913  1.43865 0.00204
## flavor1:sex1  0.25926 -0.36291  0.88143 0.24884
## flavor2:sex1  0.22222 -0.45246  0.89690 0.36767
## flavor3:sex1 -0.33333 -1.03128  0.36461 0.19534
## flavor4:sex1 -0.03704 -0.33500  0.26093 0.72777
## flavor5:sex1 -0.59259 -0.94873 -0.23646 0.00007
## flavor6:sex1 -0.55556 -1.00422 -0.10689 0.00138</code></pre>
</div>
<div id="non-parametrisch" class="section level2">
<h2>Non-parametrisch</h2>
<p>Gibbet nicht.</p>
</div>
</div>
<div id="aus-der-praxis" class="section level1">
<h1>Aus der Praxis</h1>
<div id="klassisch-1" class="section level2">
<h2>Klassisch</h2>
<div id="eda-1" class="section level3">
<h3>EDA</h3>
</div>
<div id="durchführung-1" class="section level3">
<h3>Durchführung</h3>
</div>
<div id="berichten-1" class="section level3">
<h3>Berichten</h3>
</div>
</div>
<div id="robust-1" class="section level2">
<h2>Robust</h2>
</div>
<div id="non-parametrisch-1" class="section level2">
<h2>Non-parametrisch</h2>
</div>
</div>
<div id="literatur" class="section level1 unnumbered">
<h1>Literatur</h1>
<div id="refs" class="references">
<div id="ref-Bibby.2010">
<p>Bibby, P. (2010). Simple Main Effects. In N. J. Salkind (Ed.), <em>Encyclopedia of Research Design</em>. SAGE. <a href="https://doi.org/10.4135/9781412961288.n421">https://doi.org/10.4135/9781412961288.n421</a></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
