<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Korrelation mit Messwiederholung</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="images/broom.ico">


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Chamber of Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Allgemeines
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="software.html">Software</a>
    </li>
    <li>
      <a href="r-basics.html">R Basics</a>
    </li>
    <li>
      <a href="stil.html">Stil</a>
    </li>
    <li>
      <a href="pakete.html">Pakete</a>
    </li>
    <li>
      <a href="daten-import.html">Daten-Import</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="regression.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="korrelation.html">Korrelation</a>
    </li>
    <li>
      <a href="korrelation-messwiederholung.html">Korrelation mit Messwiederholung</a>
    </li>
    <li>
      <a href="lineare-regression.html">Lineare Regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mittelwerte vergleichen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mittelwerte-vergleichen.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">t-Tests</li>
    <li>
      <a href="t-test-einstichprobe.html">Bei einer Stichprobe</a>
    </li>
    <li>
      <a href="t-test-unabhaengig.html">Bei unabhängigen Stichproben</a>
    </li>
    <li>
      <a href="t-test-abhaengig.html">Bei abhängigen Stichproben</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ANOVAs</li>
    <li>
      <a href="einfaktorielle-anova.html">Einfaktorielle ANOVA</a>
    </li>
    <li>
      <a href="faktorielle-anova.html">Faktorielle ANOVA</a>
    </li>
    <li class="dropdown-header">ANCOVA</li>
    <li>
      <a href="anova-messwiederholung.html">ANOVA mit Messwiederholung</a>
    </li>
    <li class="dropdown-header">Mixed ANOVA</li>
    <li>
      <a href="kontraste.html">Geplante Kontraste</a>
    </li>
    <li>
      <a href="post-hoc-tests.html">Post-hoc-Tests</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li>
  <a href="effektstaerken.html">Effektstärken</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-question"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="voraussetzungen.html">Voraussetzungen im GLM</a>
    </li>
    <li>
      <a href="formelsammlung.html">Formelsammlung</a>
    </li>
    <li>
      <a href="zentraler-grenzwertsatz.html">Zentraler Grenzwertsatz</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Korrelation mit Messwiederholung</h1>

</div>


<!-- Only when working on it -->
<!-- Use this after finalizing work -->
<!-- ```{r echo=FALSE, message=FALSE} -->
<!-- knitr::read_chunk("setup.R") -->
<!-- ``` -->
<!-- ```{r echo=FALSE, message=FALSE} -->
<!-- <<setup>> -->
<!-- ``` -->
<!-- Spanner Image -->
<p><img src="images/typing_r.jpg" /></p>
<p>Mit der Korrelation für Messwiederholungen <span class="citation">(<em>repeated measures correlation</em>; Bakdash &amp; Marusich, <a href="#ref-Bakdash.2017" role="doc-biblioref">2017</a>)</span> können wir die die Korrelation von zwei Variablen berechnen, die zu mehreren Messzeitpunkten erhoben wurden. Bei der <a href="korrelation.html">“normalen” Korrelation</a> haben wir die Stärke eines Zusammenhangs zwischen zwei Variablen berechnet, die einmal erhoben wurden. Es gibt aber Fälle, in denen diese beiden Variablen über mehrere Messzeitpunkte erfasst wurden. Man könnte jetzt natürlich mehrmals eine Korrelation berechnen, aber das ist irgendwie merkwürdig, denn wir Fragen uns ja, was ist denn jetzt insgesamt der Zusammenhang zwischen diesen beiden Variablen? Ein Beispiel: Jeder Psychologe kennt den <em>speed-accuracy tradeoff</em>, also das Zusammenspiel zwischen der Geschwindigkeit einer Aufgabe und der Akkuratheit, mit der man diese Aufgabe durchführt, denn je schneller man ist, desto mehr Fehler macht man üblicherweise <span class="citation">(Wickelgren, <a href="#ref-Wickelgren.1977" role="doc-biblioref">1977</a>)</span>. Um diese Aussage zu überprüfen, könnten wir untersuchen, wie Geschwindigkeit eines Probanden mit seiner Akkuratheit in einer bestimmten Aufgabe zusammenhängen.</p>
<div id="pakete" class="section level1">
<h1>Pakete</h1>
<p>Alle Berechnungen und Abbildungen können wir mit unseren <a href="pakete.html">Standardpaketen</a> durchführen. Wir benötigen das <code>tidyverse</code> zum Data Wrangling und zur Visualisierung der Daten. <code>haven</code> benötigen wir für den Import von SPSS-Dateien und <code>rstatix</code> für statistische Analysen. Wenn man sich den Import und das Bereinigen der Daten sparen möchte (Schritte, die man dennoch üben sollte), findet man die Daten auch im Paket <code>costatcompanion</code>.</p>
<p>Für dieses Verfahren benötigen wir zusätzlich das Paket <code>rmcorr</code>, das ganz normal heruntergeladen und installiert werden kann.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">library</span>(rstatix)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="kw">library</span>(costatcompanion)</span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="kw">library</span>(rmcorr)</span></code></pre></div>
</div>
<div id="beispiel" class="section level1">
<h1>Beispiel</h1>
<p>Ein klassisches Beispiel ist die “Tipp-Leistung” auf einer Tastatur. Wir könnten uns zufällig ein paar Probanden, üblicherweise Psychologie-Studenten, ins Labor einladen und ihnen über einen Bildschirm eine Liste von zufälligen Wörtern präsentieren, die sie über eine Computer-Tastatur eingeben sollen. Das lassenw ir usnere Probanden jeweils fünf Mal machen. Dabei messen wir die Geschwindigkeit, mit der sich das machen (in Tastenanschlägen pro Minute) und die Akkuratheit (in Prozent). Eine Akkuratheit von 100 bedeutet dabei, dass keine Fehler gemacht wurden, dass also eben alles akkurat und richtig eingegeben wurde.</p>
<p>Die Daten dazu finden wir entweder in der SPSS-Datei <code>typing.sav</code> oder im <a href="pakete.html#costatcompanion">Paket <code>costatcompanion</code></a> unter demselben Namen. Der Datensatz enthält zunächst die Variable <code>id</code>, in der die Probanden-ID eingetragen wurde, dann die Variable <code>trial</code>, die angibt, um den wievielten Verusch es sich für diesen Probanden handelt. <code>speed</code> ist die Geschwindigkeit eines Probanden pro Durchlauf in Tastenanschlägen pro Minute. Schließlich finden wir die “Leistung” des Probanden in der Spalte <code>accuracy</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>costatcompanion<span class="op">::</span>typing</span></code></pre></div>
<pre><code>## # A tibble: 435 x 4
##    id    trial speed accuracy
##    &lt;chr&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1 1         1  242.     48.4
##  2 1         2  242.     48.1
##  3 1         3  236.     50.2
##  4 1         4  230.     50.1
##  5 1         5  237.     48.4
##  6 2         1  251.     47.3
##  7 2         2  248.     49.0
##  8 2         3  250.     47.0
##  9 2         4  243.     48.6
## 10 2         5  239.     49.2
## # ... with 425 more rows</code></pre>
<div id="voraussetzungen" class="section level2">
<h2>Voraussetzungen</h2>
<p>Auch mit der Korrelation für Messwiederholungen bewegen wir uns im allgemeinen linearen Modell, also gelten die <a href="voraussetzungen.html">üblichen Voraussetzungen</a>. Eine Ausnahme ist die Unabhängigkeit der Messungen, die wir ja gerade explizit berücksichtigen wollen. Zudem sollten die Residuen normalverteilt sein und ein linearer Zusammenhang zwischen den beiden Variablen bestehen.</p>
</div>
<div id="eda" class="section level2">
<h2>EDA</h2>
<p>Wie immer sollten wir unsere Daten auf Ausreißer und extreme Werte kontrollieren und uns deskriptive Statistiken ausgeben lassen. Dabei gibt es schon einmal keinen Probanden, der alles falsch gemacht hat, aber durchaus welche, die fehlerfrei gearbeitet haben. Zudem haben wir Probanden dabei, die anscheinend mit dem Adler-System tippen (den FInger so lange über der Tastatur kreisen lassen, bis der zu drückende Buchstabe identifiziert ist und angegriffen werden kann) und richtig flinke FInger mit fast 600 Tastenanschlägen pro Minute. Wir werden außerdem feststellen, dass wir Daten von 87 Probanden zu jeweils fünf Messungen vorliegen haben. Zudem ist es bei Korrelationen (und Regressionen) immer eine gute Idee, die Daten als Streudiagramm abzubilden.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Deskriptive Statistiken</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>typing <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>id, <span class="op">-</span>trial) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="st">  </span><span class="kw">get_summary_stats</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 13
##   variable     n   min   max median    q1    q3   iqr   mad  mean    sd    se
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 accuracy   435  23.9  100    56.2  44.5  72.0  27.6  20.7  59.1  20.0 0.957
## 2 speed      435  60.3  548.  288.  206.  404.  198.  137.  304.  122.  5.83 
## # ... with 1 more variable: ci &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Anzahl der Probanden und Messungen</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>typing <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="st">  </span><span class="kw">count</span>(id, <span class="dt">sort =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 2
##    id        n
##    &lt;chr&gt; &lt;int&gt;
##  1 1         5
##  2 10        5
##  3 11        5
##  4 12        5
##  5 13        5
##  6 14        5
##  7 15        5
##  8 16        5
##  9 17        5
## 10 18        5
## # ... with 77 more rows</code></pre>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-5-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Hier stellen wir etwas verblüffendes fest: Eigentlich erwarten wir den <em>speed-accuracy tradeoff</em>, als eine Verringerung der <code>accuracy</code> bei höherem <code>speed</code>, aber wir scheinen genau das Gegenteil zu finden. Nach unseren Daten scheint eine höhere Geschwindigkeit der Probanden mit einer höheren Akkuratheit einherzugehen. Was stimmt denn nun? Im Prinzip tatsächlich beides.</p>
</div>
<div id="grundidee" class="section level2">
<h2>Grundidee</h2>
<p>Bei Messwiederholunegn gehen wir davon aus, dass die Daten eines einzelnen Probanden innerhalb dieses Probanden ähnlicher sind als die Daten zwischen Probanden. Uns interessiert außerdem der Zusammenhang zwischen Geschwindigkeit und Akkuratheit <em>innerhalb</em> eines Probanden, aber gemittelt für alle getesteten Probanden. Nun gibt es aber jene Probanden, die den Computer meiden wie der Teufel das Weihwasser. Auf der anderen Seite gibt es die Probanden, die vielleicht mehrere Stunden täglich am Computer arbeiten und die Tastatur benutzen müssen. Wir haben in unserer Stichprobe also die Anfänger und die Experten. Was uns jetzt nicht interessiert, ist der Zusammenhang über alle Probanden hinweg (also das, was wir in unserem Streudiagramm gezeichnet haben), sondern der intrapersonelle Zusammenhang, unabhängig von interpersonellen Eigenschaften. Genau da kommt die Korrelation mit Messwiederholungen ins Spiel. Vereinfacht gesagt nehmen wir uns den Zusammenhang jeweils pro Proband und “mitteln” diesen über alle Probanden.</p>
</div>
<div id="falsche-ansätze" class="section level2">
<h2>Falsche Ansätze</h2>
<div id="gesamte-korrelation" class="section level3">
<h3>Gesamte Korrelation</h3>
<p>Natürlich könnte man die Korrelation von <code>speed</code> und <code>accuracy</code> über alle Probanden und Messungen hinweg berechnen, also <em>zwischen</em> den Probanden und nicht <em>innerhalb</em> der Probanden. Das wollen wir zwar nicht, aber wir können es ja mal versuchen. Es ergibt sich eine sehr starke <em>positive</em> Korrelation zwischen <code>speed</code> und <code>accuracy</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>typing <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="st">  </span><span class="kw">cor_test</span>(<span class="dt">vars =</span> <span class="kw">c</span>(speed, accuracy))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##   var1  var2       cor statistic         p conf.low conf.high method 
##   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
## 1 speed accuracy  0.97      83.6 2.89e-269    0.964     0.975 Pearson</code></pre>
</div>
<div id="getrennte-korrelationen" class="section level3">
<h3>Getrennte Korrelationen</h3>
<p>Ein (verständlicher) Ansatz wäre es, die Korrelation zwischen <code>speed</code> und <code>accuracy</code> für jeden Messzeitpunkt zu errechnen. Dabei kommen wir allerdings auf 5 Korrelationskoeffizienten und betrachten den Zusammenhang wieder <em>zwischen</em> den Probanden und nicht <em>innerhalb</em> der Probanden. Auch hier ergeben sich wieder starke <em>positive</em> Korrelationen zwischen <code>speed</code> und <code>accuracy</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>typing <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="st">  </span><span class="kw">nest_by</span>(trial) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb10-4"><a href="#cb10-4"></a>    <span class="dt">correlations =</span> <span class="kw">list</span>(<span class="kw">cor_test</span>(data, <span class="dt">vars =</span> <span class="kw">c</span>(speed, accuracy)))</span>
<span id="cb10-5"><a href="#cb10-5"></a>  ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-6"><a href="#cb10-6"></a><span class="st">  </span><span class="kw">unnest</span>(correlations)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 10
## # Groups:   trial [5]
##   trial      data var1  var2    cor statistic        p conf.low conf.high method
##   &lt;int&gt; &lt;list&lt;tb&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; 
## 1     1  [87 x 3] speed accu~  0.97      38.1 3.20e-55    0.957     0.982 Pears~
## 2     2  [87 x 3] speed accu~  0.97      36.6 8.57e-54    0.954     0.980 Pears~
## 3     3  [87 x 3] speed accu~  0.97      35.8 4.58e-53    0.952     0.979 Pears~
## 4     4  [87 x 3] speed accu~  0.97      36.4 1.30e-53    0.953     0.980 Pears~
## 5     5  [87 x 3] speed accu~  0.97      40.2 4.78e-57    0.961     0.983 Pears~</code></pre>
</div>
<div id="mittelwerte-pro-proband" class="section level3">
<h3>Mittelwerte pro Proband</h3>
<p>Genauso verheerend ist es, erst die Mittelwerte pro Proband zu ermitteln und dann eine einfache Korrelation, weil wir genau den Zusammenhang <em>innerhalb</em> der Probanden, den wir ermitteln wollen, durch die Bildung des Mittelwerts eliminieren. Übrig belibt der nicht gewollte Zusammenhang <em>zwischen</em> den Probanden.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># Mittelwert von speed und accuracy pro Proband</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>participant_means &lt;-<span class="st"> </span>typing <span class="op">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="st">  </span><span class="kw">group_by</span>(id) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">across</span>(<span class="kw">c</span>(speed, accuracy), mean))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Korrelation dieser Mittelwerte</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>participant_means <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb14-3"><a href="#cb14-3"></a><span class="st">  </span><span class="kw">cor_test</span>(<span class="dt">vars =</span> <span class="kw">c</span>(speed, accuracy))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##   var1  var2       cor statistic        p conf.low conf.high method 
##   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
## 1 speed accuracy  0.97      39.1 4.04e-56    0.959     0.983 Pearson</code></pre>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-9-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Warum gehe ich so ausführlich auf das ein, was falsch ist? Weil es immer noch oft gemacht wird, und ich ein Bewusstsein dafür schaffen möchte, dass es anders gehen muss.</p>
</div>
</div>
<div id="durchführung" class="section level2">
<h2>Durchführung</h2>
<p>Das richtige Verfahren ist, wie gesagt, die Korrelation für Messwiederholungen. Diese ist mit der Funktion <code>rmcorr()</code> sehr einfach durchzuführen. Das Ergebnis speichern wir in einem Objekt, dessen Namen wir frei bestimmen. Um nun endlich die Korrelation zu erhalten, rufen wir das Objekt einfach auf. Unter Umständen erhält man eine Warnung darüber, dass die Variable, die die Probanden angibt (in diesem Falle <code>id</code>) in einen Faktor überführt wurde. Das können wir einfach so hinnehmen und muss uns nicht weiter stören.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>rm_typing &lt;-<span class="st"> </span><span class="kw">rmcorr</span>(<span class="dt">participant =</span> <span class="st">&quot;id&quot;</span>, <span class="dt">measure1 =</span> speed, <span class="dt">measure2 =</span> accuracy, <span class="dt">dataset =</span> typing)</span>
<span id="cb16-2"><a href="#cb16-2"></a></span>
<span id="cb16-3"><a href="#cb16-3"></a>rm_typing</span></code></pre></div>
<pre><code>## 
## Repeated measures correlation
## 
## r
## -0.7969593
## 
## degrees of freedom
## 347
## 
## p-value
## 5.719434e-78
## 
## 95% confidence interval
## -0.8323987 -0.7550281</code></pre>
<p>Und tatsächlich erhalten wir hier eine signifikante, negative Korrelation zwischen <code>speed</code> und <code>accuracy</code>, <span class="math inline">\(r_{rm}(347) = -.80, 95\% \text{CI} [-.83, -.76], p &lt; .001\)</span>. Was hat <code>rmcorr()</code> nun unter der Haube gemacht? Es hat den Zusammenhang zwischen unseren beiden Variablen <em>innerhalb</em> der Probanden betrachtet. Das ist fast so, also würde man für jeden Probanden eine eigene Regressionsgerade einzeichnen, allerdings mit einigen Einschränkungen (bspw. haben alle Geraden pro Proband bei dieser Methode dieselbe Steigung).</p>
<p>Das kann man sich auch mit dem nativen R-Befehl <code>plot()</code> ansehen. Hier sieht man, wie jeder Proband eine eigene Farbe bekommen hat und pro Proband eine “Regressionsgerade” geschätzt wurde. Zusätzlich kann man sich mit dem Argument <code>overall = TRUE</code> anzeigen lassen, wie die Korrelation aussehen würde, wenn wir die Messwiederholung <em>nicht</em> beachten würden.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="kw">plot</span>(rm_typing)</span></code></pre></div>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-11-1.png" width="2450" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="kw">plot</span>(rm_typing, <span class="dt">overall =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-12-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Wie man sich diese nützliche Abbildung mit dem umfangreichen <code>ggplot2</code> erstellen kann, betrachten wir bei Multilevel Linear Models.</p>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-13-1.png" width="2450" style="display: block; margin: auto;" /></p>
</div>
<div id="berichten" class="section level2">
<h2>Berichten</h2>
<p>We found a negative, significant repeated measures correlation between speed and accuracy, indicating less accuracy with greater speed in a typing task, <span class="math inline">\(r_{rm}(347) = -.80, 95\% \text{CI} [-.83, -.76], p &lt; .001\)</span>.</p>
</div>
</div>
<div id="aus-der-praxis" class="section level1">
<h1>Aus der Praxis</h1>
<p><span class="citation">Claus et al. (<a href="#ref-Claus.2020" role="doc-biblioref">2020</a>)</span> haben sich den Placebo-Effekt von Antidepressiva vorgenommen. Ein Großteil, wenn nicht sogar die gesamte der Wirkung, von Antidepressiva ist nämlich auf den Placebo-Effekt zurückzuführen <span class="citation">(Kirsch, <a href="#ref-Kirsch.2010" role="doc-biblioref">2010</a>; Moncrieff et al., <a href="#ref-Moncrieff.2004" role="doc-biblioref">2004</a>; Whitaker, <a href="#ref-Whitaker.2015" role="doc-biblioref">2015</a>)</span>. Sollte dem tatsächlich so sein, dann könnte man die Wirkung von Antidepressiva deutlich erhöhen, indem man den Placebo-Effekt an sich verstärkt. Genau das versuchten die Autoren, indem sie eine kognitiv-verhaltenstherapeutische Intervention entwickelten, die genau diesen Effekt für Patienten mit uniplorarer depressiver STörung direkt verstärken sollte. Diese Intervention testeten sie im Rahmen einer randomisierten Kontrollstudie auf ihre Wirksamkeit. Einer der treibenden Kräfte des Placebo-Effekts scheint die Erwartung eines Patienten zu sein, auf jeden Fall eine Verbesserung zu erleben <span class="citation">(<span class="citeproc-not-found" data-reference-id="Kirsch.2011"><strong>???</strong></span>)</span>. Diese Erwartung, so wie andere klinische Maße, erhoben sie in vier aufeinanderfolgenden Wochen an ihren Patienten.</p>
<p>Die Daten lassen sich in der Datei <code>placebo_amplification.sav</code> oder <a href="pakete.html#costatcompanion">Paket <code>costatcompanion</code></a> unter demselben Namen. Die Erwartung eines Patienten, durch die Therapie sicher eine Verbesserung zu erwarten, ist in der Variable <code>exp_certain</code> zu finden und kann Werte zwischen 0 und 100 annehmen (Überzeugungsrating in Prozent). Die Autoren interessierte vor allen Dingen die selbst eingeschätzte Depressivität der Patienten, die sie mit Becks Depressions-Inventar (BDI) erhoben haben, dessen Daten in der Variable <code>bdi</code> zu finden sind.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>costatcompanion<span class="op">::</span>placebo_amplification</span></code></pre></div>
<pre><code>## # A tibble: 172 x 13
##    id      age sex   treatment measurement exp_size exp_certain exp_speed cgi_s
##    &lt;chr&gt; &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;     &lt;chr&gt;          &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 1        54 Male  TAU       1               74.0        12.5      92.7     6
##  2 1        54 Male  TAU       2               79.8        13.8      88.3     4
##  3 1        54 Male  TAU       3               85.1        14.9      86.2     4
##  4 1        54 Male  TAU       4               29.8        16.0      70.2     4
##  5 2        52 Fema~ EG        1               75.9        61.0      45.3     5
##  6 2        52 Fema~ EG        2               71.3        56.4      41.5     5
##  7 2        52 Fema~ EG        3               67.0        54.3      64.9     3
##  8 2        52 Fema~ EG        4               64.9        59.6      80.8     3
##  9 3        54 Male  EG        1               92.6        71.6     100       6
## 10 3        54 Male  EG        2               79.8        94.7     100       5
## # ... with 162 more rows, and 4 more variables: bdi &lt;dbl&gt;, shaps &lt;dbl&gt;,
## #   who &lt;dbl&gt;, hamd &lt;dbl&gt;</code></pre>
<div id="eda-1" class="section level2">
<h2>EDA</h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>placebo_amplification <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="st">  </span><span class="kw">select</span>(exp_certain, bdi) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="st">  </span><span class="kw">get_summary_stats</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 13
##   variable     n   min   max median    q1    q3   iqr   mad  mean    sd    se
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 bdi        163     2    55   29    22.5  38    15.5  11.9  29.6  11.5 0.904
## 2 exp_cer~   163     0   100   47.6  18.3  72.8  54.5  41.1  46.8  30.8 2.41 
## # ... with 1 more variable: ci &lt;dbl&gt;</code></pre>
<p><img src="korrelation-messwiederholung_files/figure-html/unnamed-chunk-16-1.png" width="2450" style="display: block; margin: auto;" /></p>
</div>
<div id="durchführung-1" class="section level2">
<h2>Durchführung</h2>
<p>Die Durchführung ist wie immer kurz und schmerzlos.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="kw">rmcorr</span>(<span class="st">&quot;id&quot;</span>, <span class="dt">measure1 =</span> exp_certain, <span class="dt">measure2 =</span> bdi, <span class="dt">dataset =</span> placebo_amplification)</span></code></pre></div>
<pre><code>## 
## Repeated measures correlation
## 
## r
## -0.4938562
## 
## degrees of freedom
## 119
## 
## p-value
## 8.60642e-09
## 
## 95% confidence interval
## -0.6188418 -0.3444824</code></pre>
</div>
<div id="berichten-1" class="section level2">
<h2>Berichten</h2>
<p>We found the expected size of an improvement to be significantly and negatively correlated with the patients’ BDI-scores across all measurements, <span class="math inline">\(r_{rm}(119) = -.49, 95\% \text{CI} [-.62, -34], p &lt; .001\)</span>.</p>
</div>
</div>
<div id="literatur" class="section level1 unnumbered">
<h1>Literatur</h1>
<div id="refs" class="references">
<div id="ref-Bakdash.2017">
<p>Bakdash, J. Z., &amp; Marusich, L. R. (2017). Repeated Measures Correlation. <em>Frontiers in psychology</em>, <em>8</em>, 456. <a href="https://doi.org/10.3389/fpsyg.2017.00456">https://doi.org/10.3389/fpsyg.2017.00456</a></p>
</div>
<div id="ref-Claus.2020">
<p>Claus, B. B., Scherbaum, N., &amp; Bonnet, U. (2020). Effectiveness of an Adjunctive Psychotherapeutic Intervention Developed for Enhancing the Placebo Effect of Antidepressants Used within an Inpatient-Treatment Program of Major Depression: A Pragmatic Parallel-Group, Randomized Controlled Trial. <em>Psychotherapy and psychosomatics</em>, 1–3. <a href="https://doi.org/10.1159/000505855">https://doi.org/10.1159/000505855</a></p>
</div>
<div id="ref-Kirsch.2010">
<p>Kirsch, I. (2010). <em>The Emperor’s New Drugs: Exploding the Antidepressant Myth</em>.</p>
</div>
<div id="ref-Moncrieff.2004">
<p>Moncrieff, J., Wessely, S., &amp; Hardy, R. (2004). Active placebos versus antidepressants for depression. <em>The Cochrane database of systematic reviews</em>, <em>1</em>, CD003012. <a href="https://doi.org/10.1002/14651858.CD003012.pub2">https://doi.org/10.1002/14651858.CD003012.pub2</a></p>
</div>
<div id="ref-Whitaker.2015">
<p>Whitaker, R. (2015). <em>Anatomy of an Epidemic: Magic Bullets, Psychiatric Drugs, and the Astonishing Rise of Mental Illness in America</em>. Broadway Books.</p>
</div>
<div id="ref-Wickelgren.1977">
<p>Wickelgren, W. A. (1977). Speed-accuracy tradeoff and information processing dynamics. <em>Acta Psychologica</em>, <em>41</em>(1), 67–85. <a href="https://doi.org/10.1016/0001-6918(77)90012-9">https://doi.org/10.1016/0001-6918(77)90012-9</a></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
