<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lineare Regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="images/broom.ico">


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Chamber of Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Allgemeines
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="software.html">Software</a>
    </li>
    <li>
      <a href="r-basics.html">R Basics</a>
    </li>
    <li>
      <a href="stil.html">Stil</a>
    </li>
    <li>
      <a href="pakete.html">Pakete</a>
    </li>
    <li>
      <a href="daten-import.html">Daten-Import</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="regression.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="korrelation.html">Korrelation</a>
    </li>
    <li>
      <a href="korrelation-messwiederholung.html">Korrelation mit Messwiederholung</a>
    </li>
    <li>
      <a href="lineare-regression.html">Lineare Regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mittelwerte vergleichen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mittelwerte-vergleichen.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">t-Tests</li>
    <li>
      <a href="t-test-einstichprobe.html">Bei einer Stichprobe</a>
    </li>
    <li>
      <a href="t-test-unabhaengig.html">Bei unabhängigen Stichproben</a>
    </li>
    <li>
      <a href="t-test-abhaengig.html">Bei abhängigen Stichproben</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ANOVAs</li>
    <li>
      <a href="einfaktorielle-anova.html">Einfaktorielle ANOVA</a>
    </li>
    <li>
      <a href="faktorielle-anova.html">Faktorielle ANOVA</a>
    </li>
    <li class="dropdown-header">ANCOVA</li>
    <li>
      <a href="anova-messwiederholung.html">ANOVA mit Messwiederholung</a>
    </li>
    <li class="dropdown-header">Mixed ANOVA</li>
    <li>
      <a href="kontraste.html">Geplante Kontraste</a>
    </li>
    <li>
      <a href="post-hoc-tests.html">Post-hoc-Tests</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li>
  <a href="effektstaerken.html">Effektstärken</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-question"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="voraussetzungen.html">Voraussetzungen im GLM</a>
    </li>
    <li>
      <a href="formelsammlung.html">Formelsammlung</a>
    </li>
    <li>
      <a href="zentraler-grenzwertsatz.html">Zentraler Grenzwertsatz</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Lineare Regression</h1>

</div>


<!-- <!-- Only when working on it -->
<p>–&gt; <!-- ```{r echo=FALSE, message=FALSE} --> <!-- knitr::opts_chunk$set(fig.align = "center", dpi = 350) --> <!-- ggplot2::theme_set(ggplot2::theme_minimal()) --></p>
<!-- library(benelib) -->
<!-- library(patchwork) -->
<!-- library(gt) -->
<!-- ``` -->
<!-- Use this after finalizing work -->
<!-- Spanner Image -->
<p><img src="images/swimmer_r.jpg" /></p>
<p>Die linerare Regression wird genutzt, um lineare Zusammenhänge in Form eines Modells zu beschreiben, Vorhersagen zu treffen und zu überprüfen, ob Zusammenhänge und das Modell an sich “statistisch signifikant” sind. Gleichzeitig kann man an dieser Stelle die Aufteilung dieser Website infrage Stellen, da die lineare Regression (als Sonderform des Allgemeinen Linearen Modells, oder kurz GLM für <em>Generalized Linear Model</em>) z.B. auch zum Vergleich von Mittelwerten oder für Klassifikationen eingesetzt werden kann. Alle klassischen Verfahren im Abschnitt <a href="mittelwerte-vergleichen.html">“Mittelwerte vergleichen”</a> sind im Kern auch nur lineare Modelle, die einer etwas anderen Form aufgeschrieben wurden. Die zugrundeliegeden Formeln sind jedoch dieselben.</p>
<div id="pakete" class="section level1">
<h1>Pakete</h1>
<p>Alle Berechnungen und Abbildungen können wir mit unseren <a href="pakete.html">Standardpaketen</a> durchführen. Wir benötigen das <code>tidyverse</code> zum Data Wrangling und zur Visualisierung der Daten. <code>haven</code> benötigen wir für den Import von SPSS-Dateien und <code>rstatix</code> für statistische Analysen. Wenn man sich den Import und das Bereinigen der Daten sparen möchte (Schritte, die man dennoch üben sollte), findet man die Daten auch im Paket <code>costatcompanion</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">library</span>(rstatix)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="kw">library</span>(costatcompanion)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
</div>
<div id="beispiel-mit-einem-prädiktor" class="section level1">
<h1>Beispiel mit einem Prädiktor</h1>
<p>Im Kapitel zur Berechnung und Interpretationen der <a href="korrelation.html">Korrelation</a> haben wir uns den Datensatz eines kleinen Freibads angeschaut, in dem zu verschiedenen Tagen im Jahr sowohl die Besucherzahl, als auch verschiedene andere Variablen eingetragen waren. Wir haben bereits herausgefunden, dass die Temperatur an einem bestimmten Tag sehr eng mit der Anzahl der Schwimmer im Schwimmbecken korrelierte, aber können wir diesen Zusammenhang genauer beschreiben? Und wie groß ist dieser Zusammenhang? Nur weil es einen starken Zusammenhang gibt, muss das ja nicht bedeuten, dass er auch groß ist.</p>
<div id="klassisch" class="section level2">
<h2>Klassisch</h2>
<p>Wir benutzen denselben Datensatz, den wir auch bei den <a href="korrelation.html">Korrelationen</a> kennengelernt haben. Den Datensatz <code>water_park</code> finden wir also im Paket <code>costatcompanion</code>. In der ersten Spalte (<code>day_id</code>) finden wir eine individuelle ID des beobachteten Tages (in zufälliger Reihenfolge). Nachfolgend finden wir vier Variablen, die an jedem Tag gemessen wurden. Dazu zählen die Durchschnitts-Temperatur (<code>temperature</code>), die Anzahl der Schwimmer im Schwimmbecken (<code>swimmers</code>), den Tages-Umsatz des Freibad-Kiosks in Euro (<code>sales</code>) und die Anzahl der Schlägereien, wegen der die Polizei gerufen werden musste (<code>beatings</code>).</p>
<p>Wir interessieren uns für den Zusammenhang zwischen der gemessenen Temperatur mit der Anzahl der beobachteten Schwimmer im Schwimmbecken.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>costatcompanion<span class="op">::</span>water_park</span></code></pre></div>
<pre><code>## # A tibble: 100 x 5
##    day_id temperature swimmers sales beatings
##    &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1 1             28.9      106  1554        7
##  2 2             34.4      142  2261        7
##  3 3             25.1       72  1232        4
##  4 4             21.8       50   823        5
##  5 5             39        167  2661       10
##  6 6             21.4       81  1025        4
##  7 7             26.7      111  1895        7
##  8 8             25        128  2153        8
##  9 9             12.7       37   534        1
## 10 10            16.3       56   829        1
## # ... with 90 more rows</code></pre>
<div id="voraussetzungen" class="section level3">
<h3>Voraussetzungen</h3>
<p>Da wir uns im GLM bewegen, gelten die üblichen <a href="voraussetzungen.html">Voraussetzungen</a>. Vor allem sollten die Daten jedoch auf Linearität und potenzielle Ausreißer geprüft werden! Außerdem sollten die Modell-Residuen normalverteilt und die unabhängigen Variablen sollten nicht multikollinear sein. Zudem sollten die unabhängigen Variablen Varianz aufweisen.</p>
</div>
<div id="eda" class="section level3">
<h3>EDA</h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Deskriptive Statistiken</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="st">  </span><span class="kw">select</span>(temperature, swimmers) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="st">  </span><span class="kw">get_summary_stats</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 13
##   variable     n   min   max median    q1    q3   iqr   mad  mean    sd    se
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 swimmers   100  34   195     97    82   121   39    28.2  100.  30.0   3.00
## 2 tempera~   100  11.9  45.6   25.1  21.0  28.9  7.98  6.00  25.0  6.00  0.6 
## # ... with 1 more variable: ci &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Outliers</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="st">  </span><span class="kw">identify_outliers</span>(temperature)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   day_id temperature swimmers sales beatings is.outlier is.extreme
##   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
## 1 51            45.6      195  2837       10 TRUE       FALSE</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="st">  </span><span class="kw">identify_outliers</span>(swimmers)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   day_id temperature swimmers sales beatings is.outlier is.extreme
##   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
## 1 51            45.6      195  2837       10 TRUE       FALSE</code></pre>
<p>Nach den mathematischen Verfahren sind in den Variablen <code>temperature</code> und <code>swimmers</code> jeweils ein Outlier (Ausreißer) vorhanden, die wir auch in den Boxplots (s.u.) sehen. Ob diese beiden einen Einfluss auf unser Modell haben, sollten wir als Fragestellung im Hinterkopf behalten. Man sollte auf jeden Fall untersuchen, warum ein Datenpunkt ein Outlier ist. In diesem Falle ist es einfach ein besonders heißer Tag mit besonders vielen Besuchern. Wir haben also keinen Grund anzunehmen,w arum hier etwas falsch gelaufen sein könnte, deshalb lassen wir diesen Datenpunkt im Datensatz und behandeln ihn wie jeden anderen.</p>
<p><img src="lineare-regression_files/figure-html/descr_figures-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Anhand der Abbildungen können wir feststellen, dass die Verteilungen relativ regelmäßig sind und es einen linearen Zusammenhang zwischen der gemessenen Durchschnittstemperatur eines Tages und der Anzahl von Schwimmern im Schwimmbecken gibt. An dieser Stelle habe ich bereits etwas geschummelt, indem ich in die rechte Abbildung eine blaue Linie eingezeichnet habe. Das ist tatsächlich schon die regressionsgerade, die wir mit der linearen Regression schätzen/herausfinden wollen.</p>
</div>
<div id="durchführung" class="section level3">
<h3>Durchführung</h3>
<p>Diese Linie zu schätzen ist in R so einfach die Torte essen. Wir arbeiten hier hauptsächlich mit dem Befehl <code>lm()</code>, der für <em>Linear Model</em> steht. Da es sich hierbei um eine native Funktion von R handelt, ist die Schreibweise und Reihenfolge der Argumente etwas ungewont, lässt sich aber fix lernen. Wir geben als erstes Argument die Formel an, anhand derer wir einen Zusammenhäng schätzen wollen. Auf der linken Seite der Formel steht immer die abhängige Variable. Dann kommt eine Tilde (<code>~</code>) und anschließend die unabhängige(n) Variable(n), also jene, die wir heranziehen, um die abhängige Variable zu erklären. Genau so kann man die Formel dann auch lesen: <code>diese_variable ~ jene_variable</code> heißt so viel wie “Diese Variable wird erklärt durch jene Variable”. In unserem Beispiel versuchen wir die Anzahl der beobachteten Schwimmer in Abhänigkeit der gemessenen Durchschnittstemperatur vorherzusagen, also lautet unsere Formel <code>swimmers ~ temperature</code>. Als zweites Argument geben wir den Datensatz an, der dem Modell zugrunde liegen soll (in diesem Falle <code>water_park</code>). Bei <strong>fehlenden Werten</strong> sollte man das Argument <code>na.action = na.exclude</code> mitgeben, da es sonst zu einem Fehler kommt und R kein Ergebnis ausspuckt (weil es nicht weiß, wie es mit fehlenden Werten umgehen soll).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="kw">lm</span>(swimmers <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> water_park)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = swimmers ~ temperature, data = water_park)
## 
## Coefficients:
## (Intercept)  temperature  
##      -7.473        4.297</code></pre>
<p>Wenn wir diesen Befehl ausführen, bekommen wir einen recht sparsamen Überblick über das geschätzte Modell, d.h. den <span class="math inline">\(y\)</span>-Achsen-Abschnitt und die Steigung der geschätzten Gerade. Um noch mehr aus diesem Modell zu quätschen, müssen wir uns eine Zusammenfassung ansehen, die wir mit der Funktion <code>summary()</code> erhalten. Dabei kann man zwei Wege wählen: Entweder speichert man das geschätzte Modell in einer Variablen, oder man “pipet” das Modell direkt in die Funktion <code>summary()</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Erste Möglichkeit</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>water_model &lt;-<span class="st"> </span><span class="kw">lm</span>(swimmers <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> water_park)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="kw">summary</span>(water_model)</span>
<span id="cb16-4"><a href="#cb16-4"></a></span>
<span id="cb16-5"><a href="#cb16-5"></a><span class="co"># Zweite Möglichkeit</span></span>
<span id="cb16-6"><a href="#cb16-6"></a><span class="kw">lm</span>(swimmers <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> water_park) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb16-7"><a href="#cb16-7"></a><span class="st">  </span><span class="kw">summary</span>()</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = swimmers ~ temperature, data = water_park)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -44.229  -8.395   1.770  10.281  30.668 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -7.4729     6.6247  -1.128    0.262    
## temperature   4.2965     0.2577  16.675   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.39 on 98 degrees of freedom
## Multiple R-squared:  0.7394, Adjusted R-squared:  0.7367 
## F-statistic:   278 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Beide Möglichkeiten führen zum identischen Ergebnis. Es ist jedoch immer eine gute Idee, das geschätzte Modell an sich abzuspeichern, um damit noch andere Dinge anzustellen. Der Output entspricht so gar nicht unserem “tidy way of life”, den wir durch die Benutzung des <a href="pakete.html">Tidyverse</a> leben wollen. Gucken wir ihn uns trotzdem einmal an:</p>
<ul>
<li>Wir erhalten eine Info über den eigentlichen <em>Call</em>, also den Befehl, den wir zur Erstellung des Modells eingegeben haben</li>
<li>anschließend gibt es eine Übersicht über die Residuen des Modells</li>
<li>dann die Koeffizienten mit entsprechenden Signifikanztests</li>
<li>und einige Angaben zum Modell an sich</li>
</ul>
<p>Anhand des Outputs können wir feststellen, dass der Einfluss der Temperatur auf die beobachtete Anzahl der Schwimmer signifikant ist, <span class="math inline">\(b_1 = 4.30, p &lt; .001\)</span>. Wie interpretiert man diesen Koeffizienten nun? Der Regressionskoeffizient eines <strong>Prädiktors</strong> (einer unabhängigen Variable) sagt und immer folgendes: <strong>Erhöht man diesen Prädiktor um eine Einheit, dann ändert sich das Kriterium (die abhängige Variable) um genau diese Menge</strong>. In diesem Fall bedeutet das also: Steigt die Durchschnittstemperatur um 1 Grad Celsius, dann werden 4.30 Schwimmer mehr beobachtet, bzw. <em>geschätzt</em>. Zudem erhalten wir <span class="math inline">\(R^2\)</span> (den <strong>Determinationskoeffizienten</strong>, bzw. das <strong>Bestimmtheitsmaß</strong>) und seine korrigierte Form, <span class="math inline">\(R^2_\text{adj}\)</span>. Man sollte immer die korrigierte Version, also <span class="math inline">\(R^2_\text{adj}\)</span> angeben, was in diesem Fall <span class="math inline">\(R^2_\text{adj} = .737\)</span> ist und uns sagt, dass wir durch unser lineares Modell 73.7% der Varianz in den Daten erklären können. Ob dieser Wert größer als 0 ist, kann uns der <span class="math inline">\(F\)</span>-Test sagen, der ebenfalls mit ausgegeben wird (ganz am Ende des Outputs). Dieser ist signifikant, <span class="math inline">\(F(1, 98) = 278, p &lt; .001\)</span>, also ist <span class="math inline">\(R^2 &gt; 0\)</span>.</p>
</div>
<div id="tidy-modelle" class="section level3">
<h3>Tidy Modelle</h3>
<p>Um unsere Grundphilosophie nicht ins Wanken zu bringen, können wir das Paket <a href="https://broom.tidymodels.org/"><code>broom</code></a> nutzen, dass “messy” Outputs, wie den der Funktion <code>lm()</code> nimmt und “tidy” macht. Dafür beinhaltet das Paket drei Grundfunktionen, deren Nutzen man grob kennen sollte.</p>
<ul>
<li><code>tidy()</code> nimmt die Koeffizienten eines Modells und überführt diese in eine saubere Tabelle (<em>tibble</em>)</li>
<li><code>glance()</code> nimmt die Angaben zur Modellgüte und überführt diese ebenfalls in eine saubere Tabelle (<em>tibble</em>)</li>
<li><code>augment()</code> nimmt Angaben zu jedem originalen Datenpunkt (z.B. die Residuen) und fügt diese dem Datensatz hinzu</li>
</ul>
<p>Wer das Paket noch nicht installiert hat, kann dies wie immer ganz einfach nachholen.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;broom&quot;</span>)</span>
<span id="cb18-2"><a href="#cb18-2"></a></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="kw">library</span>(broom)</span></code></pre></div>
<p>Wenn wir uns die Koeffizienten mit Signifikanztests ausgeben lassen wollen, nutzen wir also <code>tidy()</code>. So erhalten wir eine ganz simple, saubere und allumfassende Übersicht über unsere Modell-Koeffizienten.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="kw">tidy</span>(water_model)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    -7.47     6.62      -1.13 2.62e- 1
## 2 temperature     4.30     0.258     16.7  2.25e-30</code></pre>
<p>Angaben zur Modellgüte können wir mit <code>glance()</code> auslesen. Hier bekommen wir sogar wesentlich mehr Informationen als durch die normale <code>summary()</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="kw">glance</span>(water_model)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.739         0.737  15.4      278. 2.25e-30     1  -414.  834.  842.
## # ... with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>Residuen, Distanzen und ähnliches werden mit <code>augment()</code> an den ursprünglichen Datensatz angehängt.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="kw">augment</span>(water_model)</span></code></pre></div>
<pre><code>## # A tibble: 100 x 8
##    swimmers temperature .fitted .resid .std.resid   .hat .sigma  .cooksd
##       &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
##  1      106        28.9   117.  -10.7      -0.700 0.0142   15.4 0.00354 
##  2      142        34.4   140.    1.67      0.111 0.0347   15.5 0.000220
##  3       72        25.1   100.  -28.4      -1.85  0.0100   15.2 0.0173  
##  4       50        21.8    86.2 -36.2      -2.37  0.0129   15.0 0.0366  
##  5      167        39     160.    6.91      0.464 0.0649   15.4 0.00748 
##  6       81        21.4    84.5  -3.47     -0.227 0.0136   15.5 0.000357
##  7      111        26.7   107.    3.76      0.245 0.0108   15.5 0.000329
##  8      128        25      99.9  28.1       1.83  0.0100   15.2 0.0170  
##  9       37        12.7    47.1 -10.1      -0.674 0.0525   15.4 0.0126  
## 10       56        16.3    62.6  -6.56     -0.433 0.0313   15.5 0.00303 
## # ... with 90 more rows</code></pre>
<p>Die angehängten Variablen sind netteweise mit einem “.” als Präfix versehne, wodurch wir erkennen können, welche Werte neu sind. Wir erhalten die geschätzten Werte (<code>.fitted</code>), die im Grunde die Werte einer jeden Beobachtung auf der Regressionsgeraden sind. Dann erhalten wir die rohen Residuen (<code>.resid</code>) und die standardisierten Residuen (<code>.std.resid</code>), sowie die Hebelwerte (<em>hat values</em>, <code>.hat</code>), den Cook-Abstand (<code>.cooksd</code>) und die Standardabweichung der Residuen, wenn die jeweilige Beobachtung ausgeschlossen werden würde (<code>.sigma</code>).</p>
</div>
<div id="modell-diagnostik" class="section level3">
<h3>Modell-Diagnostik</h3>
<p>Vor allem mit den Ergebnissen von <code>augment()</code> können wir die Voraussetzungen einer linearen Regression prüfen. Unter anderem sollen die</p>
<ul>
<li><strong>Residuen</strong> normalverteilt,</li>
<li>der Betrag eines standardisierten Residuums nicht größer 3.29 <span class="citation">(Field, <a href="#ref-Field.2018" role="doc-biblioref">2018</a>)</span>,</li>
<li>Cook-Abstand nicht größer als 1 sein <span class="citation">(Cook &amp; Weisberg, <a href="#ref-Cook.1982" role="doc-biblioref">1982</a>)</span>,</li>
<li>und die Hebelwerte (<em>hat values</em>) nicht größer als zweimal der durchschnittliche Hebelwert <span class="citation">(Hoaglin &amp; Welsch, <a href="#ref-Hoaglin.1978" role="doc-biblioref">1978</a>)</span>. Der durchschnittliche Hebelwert ist <span class="math display">\[\dfrac{(k+1)}{n}\]</span> mit <span class="math inline">\(k\)</span> als Anzahl der Prädiktoren und <span class="math inline">\(n\)</span> als Anzahl der Beobachtungen. Somit sollte der Betrag der <em>hat values</em> nicht größer sein als<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> <span class="math display">\[2 \cdot \dfrac{(k+1)}{n}\]</span></li>
</ul>
<p>Das könnten wir nun ganz einfach überprüfen. Da das jedoch Schritte sind, die wir für jede Regression durchlaufen sollten, und sie somit Standard sind, gibt es kluge Köpfe, die Abbildungen zur Modelldiagnostik für verschiedenen Verfahren im Paket <a href="https://github.com/sinhrks/ggfortify"><code>ggfortify</code></a> zusammengestellt haben.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;ggfortify&quot;</span>)</span>
<span id="cb25-2"><a href="#cb25-2"></a></span>
<span id="cb25-3"><a href="#cb25-3"></a><span class="kw">library</span>(ggfortify)</span></code></pre></div>
<p>Diese Abbildungen sehen für unser Modell folgendermaßen aus. In diesem Fall ist alles im großen und ganzen in Ordnung.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="kw">autoplot</span>(water_model, <span class="dt">which =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## Warning: `arrange_()` is deprecated as of dplyr 0.7.0.
## Please use `arrange()` instead.
## See vignette(&#39;programming&#39;) for more help
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<p><img src="lineare-regression_files/figure-html/unnamed-chunk-14-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p>Natürlich können wir die oben dargestellten Kriterien zur Modell-Diagnostik auch an “harten Zahlen” prüfen und müssen uns nicht auf Abbildungen verlassen. Wobei wir die Normalverteilung von Variablen doch schon anhand eines QQ-Plots beurteilen sollten (Abbildung “Normal Q-Q”, die von <code>ggfortif</code> ausgegeben wird), was in diesem Falle in Ordnung war. Des weiteren sollte der Betrag eines standardisierten Residuums nicht größer als 3.29 sein. Auch sollte der Cook-Abstand kleiner gleich 1 sein (also nicht größer als 1) und die Hebelwerte kleiner als der doppelte durchschnittliche Hebelwert. Das können wir mithilfe von <code>augment()</code> ganz einfach lösen. Zunächst berechnen wir jedoch die Schwelle für problematische Hebelwerte nach der obigen Formel.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># Anzahl der Prädiktoren</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>k &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb28-3"><a href="#cb28-3"></a></span>
<span id="cb28-4"><a href="#cb28-4"></a><span class="co"># Anzahl der Beobachtungen</span></span>
<span id="cb28-5"><a href="#cb28-5"></a>n &lt;-<span class="st"> </span><span class="kw">nrow</span>(water_park)</span>
<span id="cb28-6"><a href="#cb28-6"></a></span>
<span id="cb28-7"><a href="#cb28-7"></a>hat_threshold &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(k <span class="op">+</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>n</span></code></pre></div>
<p>Hebelwerte, die größer als 0.04 sind, sollten also untersucht werden. Um unsere Diagnostiken zu berechnen, erstellen wir mit <code>mutate()</code> einfach vier neue Variablen: Jeweils eine, die angibt, wenn es ein Problem in dem jeweiligen Diagnostik-Outcome gibt (codiert als 1) und dann die Summe dieser Variablen. Weist ein Fall “keine Probleme” auf, dann hat er in diesen neuen Variablen einen Wert von jeweils 0 und somit ist auch die Summe dieser neuen Variablen 0. Ist ein Wert problematisch, ergibt das in der Summe 1, bei zwei problematischen Werten 2 und wenn alle drei Werte problematisch sind, dann ergibt die Summe 3. Anschließend können wir uns jene Fälle rausfiltern, in denen Probleme aufgetreten sind.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>water_augmented &lt;-<span class="st"> </span><span class="kw">augment</span>(water_model)</span>
<span id="cb29-2"><a href="#cb29-2"></a></span>
<span id="cb29-3"><a href="#cb29-3"></a>water_augmented <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-4"><a href="#cb29-4"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb29-5"><a href="#cb29-5"></a>    <span class="dt">diag_resid =</span> <span class="kw">if_else</span>(<span class="kw">abs</span>(.std.resid) <span class="op">&gt;</span><span class="st"> </span><span class="fl">3.29</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-6"><a href="#cb29-6"></a>    <span class="dt">diag_cook =</span> <span class="kw">if_else</span>(.cooksd <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-7"><a href="#cb29-7"></a>    <span class="dt">diag_hat =</span> <span class="kw">if_else</span>(.hat <span class="op">&gt;</span><span class="st"> </span>hat_threshold, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-8"><a href="#cb29-8"></a>    <span class="dt">diag_sum =</span> diag_resid <span class="op">+</span><span class="st"> </span>diag_cook <span class="op">+</span><span class="st"> </span>diag_hat</span>
<span id="cb29-9"><a href="#cb29-9"></a>  ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-10"><a href="#cb29-10"></a><span class="st">  </span><span class="kw">filter</span>(diag_sum <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 12
##   swimmers temperature .fitted  .resid .std.resid   .hat .sigma .cooksd
##      &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1      167        39     160.    6.91      0.464  0.0649   15.4 7.48e-3
## 2       37        12.7    47.1 -10.1      -0.674  0.0525   15.4 1.26e-2
## 3       48        11.9    43.7   4.34      0.291  0.0582   15.5 2.61e-3
## 4      147        36.9   151.   -4.07     -0.271  0.0497   15.5 1.92e-3
## 5      195        45.6   188.    6.55      0.456  0.129    15.5 1.54e-2
## 6       44        12.2    44.9  -0.945    -0.0632 0.0560   15.5 1.18e-4
## # ... with 4 more variables: diag_resid &lt;dbl&gt;, diag_cook &lt;dbl&gt;, diag_hat &lt;dbl&gt;,
## #   diag_sum &lt;dbl&gt;</code></pre>
<p>Wir erhalten somit 6 Fälle in denen die Hebelwerte größer als die errechnete Schwelle (0.04) sind. Was macht man jetzt mit einem solchen Ergebnis? Man diskutiert es! <strong>Fälle einfach auf Basis problematischer Diagnostiken auszuschließen, geht nicht!</strong> Diese Diagnostiken sind nur ein Mittel, um zu beurteilen, wie gut oder schlecht unser Modell ist. In diesem Fall sind 4 von 100 Hebelwerten leicht über der errechneten Schwelle (zwei sind deutlich darüber). Das Modell ist also gar nicht so schlecht und wir können es so beibehalten. O ### Berichten We found the mean daily temperature to predict te amount of swimmers in a pool significantly. The overall model was statistically significant, <span class="math inline">\(F(1, 98) = 278, p &lt; .001, R^2_\text{adj} = .737\)</span>. The model coefficients can be found in the following table.</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#iucuzkrrkg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#iucuzkrrkg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iucuzkrrkg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iucuzkrrkg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iucuzkrrkg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iucuzkrrkg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iucuzkrrkg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#iucuzkrrkg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#iucuzkrrkg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#iucuzkrrkg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#iucuzkrrkg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#iucuzkrrkg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#iucuzkrrkg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#iucuzkrrkg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#iucuzkrrkg .gt_from_md > :first-child {
  margin-top: 0;
}

#iucuzkrrkg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iucuzkrrkg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iucuzkrrkg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#iucuzkrrkg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iucuzkrrkg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#iucuzkrrkg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iucuzkrrkg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iucuzkrrkg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iucuzkrrkg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iucuzkrrkg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#iucuzkrrkg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iucuzkrrkg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#iucuzkrrkg .gt_left {
  text-align: left;
}

#iucuzkrrkg .gt_center {
  text-align: center;
}

#iucuzkrrkg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iucuzkrrkg .gt_font_normal {
  font-weight: normal;
}

#iucuzkrrkg .gt_font_bold {
  font-weight: bold;
}

#iucuzkrrkg .gt_font_italic {
  font-style: italic;
}

#iucuzkrrkg .gt_super {
  font-size: 65%;
}

#iucuzkrrkg .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="iucuzkrrkg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><em>b</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><em>SE</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><em>t</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><em>p</em></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">(Intercept)</td>
      <td class="gt_row gt_center">&minus;7.473</td>
      <td class="gt_row gt_center">6.625</td>
      <td class="gt_row gt_center">&minus;1.128</td>
      <td class="gt_row gt_center">0.262</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">temperature</td>
      <td class="gt_row gt_center">4.297</td>
      <td class="gt_row gt_center">0.258</td>
      <td class="gt_row gt_center">16.675</td>
      <td class="gt_row gt_center">< .001</td>
    </tr>
  </tbody>
  
  
</table></div>
</div>
</div>
<div id="robust" class="section level2">
<h2>Robust</h2>
<p>Folgt.</p>
</div>
</div>
<div id="beispiel-mit-mehreren-prädiktoren" class="section level1">
<h1>Beispiel mit mehreren Prädiktoren</h1>
<p>Einige aufmerksame Leser werden bereits festgestelt haben, dass es im Datensatz <code>water_park</code> mehr als nur zwei Variablen (<code>swimmers</code> und <code>temperature</code>) gibt. Es findet sich auch eine Variable <code>sales</code>, mit der die Umsätze des Freibad-Kiosks in Euro festgehalten ist, sowie die Variable <code>beatings</code>, in der die Anzahl der Schlägereien aufgeführt ist, wegen derer die Polizei gerufen werden musste.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>water_park</span></code></pre></div>
<pre><code>## # A tibble: 100 x 5
##    day_id temperature swimmers sales beatings
##    &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1 1             28.9      106  1554        7
##  2 2             34.4      142  2261        7
##  3 3             25.1       72  1232        4
##  4 4             21.8       50   823        5
##  5 5             39        167  2661       10
##  6 6             21.4       81  1025        4
##  7 7             26.7      111  1895        7
##  8 8             25        128  2153        8
##  9 9             12.7       37   534        1
## 10 10            16.3       56   829        1
## # ... with 90 more rows</code></pre>
<p>Wir ändern unsere Fragestellung etwas und fragen nun: Können wir die Anzahl der Schlägereien durch die anderen Variablen erklären? Na klar! Außer, dass wir jetzt weitere Variablen als Prädiktoren benutzen, ändert sich nichts. Dennoch geben wir dem ganzen einen neuen Namen: <strong>Multiple Regression</strong> (also eine lineare Regression mit mehreren Prädiktoren).</p>
<div id="eda-1" class="section level2">
<h2>EDA</h2>
<p>Zu Beginn ist es immer ratsam zu untersuchen, ob die potenziellen Prädiktoren keine Ausreißer enthalten und mit dem Kriterium (der abhängigen Variable) linear zusammenhängen. Dafür nutzen wir wieder deskriptive Statistiken und Abbildungen. Um zu überprüfen, wie stark die potenziellen Prädiktoren mit dem Kriterium (Anzahl der Schlägereien) zusammenhängen, können wir auch Korrelationen berechnen.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-2"><a href="#cb33-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>day_id) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="st">  </span><span class="kw">get_summary_stats</span>()</span></code></pre></div>
<pre><code>## # A tibble: 4 x 13
##   variable     n   min    max median     q1     q3    iqr    mad   mean     sd
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 beatings   100   1     11      5      4      6     2      1.48 5.01e0   2.02
## 2 sales      100 410   2837   1476   1156.  1861.  706.   554.   1.50e3 500.  
## 3 swimmers   100  34    195     97     82    121    39     28.2  1.00e2  30.0 
## 4 tempera~   100  11.9   45.6   25.1   21.0   28.9   7.98   6.00 2.50e1   6.00
## # ... with 2 more variables: se &lt;dbl&gt;, ci &lt;dbl&gt;</code></pre>
<p><img src="lineare-regression_files/figure-html/unnamed-chunk-20-1.png" width="2450" style="display: block; margin: auto;" /></p>
<p><img src="lineare-regression_files/figure-html/unnamed-chunk-21-1.png" width="1050" style="display: block; margin: auto;" /></p>
<p>Wir können so relativ leicht erkennen, dass alle potenziellen Prädiktoren mit dem Kriterium <code>beatings</code> signifikant korrelieren. Ein Problem könnte jedoch auftreten, wenn die Prädiktoren “zu gut” miteinander korrelieren; dieses Problem nennt man Multikollinearität.</p>
</div>
<div id="multikollinearität" class="section level2">
<h2>Multikollinearität</h2>
<p><strong>Multikollinearität</strong> ist ein Problem und tritt bei linearen Regressionen auf, wenn zwei oder mehr Prädiktoren zu hohe Korrelationen miteinander haben. Das sorgt dafür, dass die Schätzungen der Modellparameter ungenau bis falsch werden, aber auch die Modellinterpretation kann problematisch werden, wenn Prädiktoren miteinander hoch korreliert sind. Eine Möglichkeit, Multikollinearität aufzudecken, ist die Analyse der Korrelationen der Prädiktoren untereinander. Aus der obigen Abbildung geht hervor, dass die höchste Korrelation zwischen den Prädiktoren <span class="math inline">\(r = .95\)</span> ist (jene zwischen der Anzahl der Schwimmer und dem Kiosk-Umsatz), was probleatisch sein könnte.</p>
<p>Eine weitere Möglichkeit ist der sogenannte <strong>Varianzinflationsfaktor (VIF)</strong> oder sein Kehrwert, die <strong>Toleranz</strong>. Im Paket <code>car</code> gibt es die Funktion <code>vif()</code> die ein lineares Modell als Argument nimmt und uns den VIF berechnet. Nach <span class="citation">Field (<a href="#ref-Field.2018" role="doc-biblioref">2018</a>)</span> sind Werte größer 10 ein Problem. Wir müssen das Modell also einmal schätzen, um uns den VIF für jeden Prädiktor ausgeben zu lassen. Das Modell erweitern wir mit einem ganz normalen <code>+</code>. Wer das Paket <code>car</code> noch nicht installiert hat, kann das natürlich sofort nachholen.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb35-2"><a href="#cb35-2"></a></span>
<span id="cb35-3"><a href="#cb35-3"></a><span class="kw">library</span>(car)</span></code></pre></div>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>water_big_model &lt;-<span class="st"> </span><span class="kw">lm</span>(beatings <span class="op">~</span><span class="st"> </span>swimmers <span class="op">+</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>sales, <span class="dt">data =</span> water_park)</span>
<span id="cb36-2"><a href="#cb36-2"></a></span>
<span id="cb36-3"><a href="#cb36-3"></a><span class="kw">vif</span>(water_big_model)</span></code></pre></div>
<pre><code>##    swimmers temperature       sales 
##   15.359204    3.954328   10.640960</code></pre>
<p>Der VIF von <code>swimmers</code> ist mit 15.36 deutlich über 10 und wir sollten darüber nachdenken, diesen zu entfernen. Das machen wir nun auch und gucken uns den VIF dann erneut an.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>water_medium_model &lt;-<span class="st"> </span><span class="kw">lm</span>(beatings <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>sales, <span class="dt">data =</span> water_park)</span>
<span id="cb38-2"><a href="#cb38-2"></a></span>
<span id="cb38-3"><a href="#cb38-3"></a><span class="kw">vif</span>(water_medium_model)</span></code></pre></div>
<pre><code>## temperature       sales 
##    2.658403    2.658403</code></pre>
<p>Und schon haben wir kein Problem mehr.</p>
</div>
<div id="modell" class="section level2">
<h2>Modell</h2>
<p>Das Modell haben wir im vorigen Schritt bereits definiert und schätzen lassen, können es uns also direkt anschauen. Wir haben ein im allgemeinen signifikantes Modell, das viel Varianz aufklärt, <span class="math inline">\(F(2, 97) = 69.7, p &lt; .001, R^2_\text{adj} = .581\)</span>. Außerdem sind alle Prädiktoren signifikant, da alle <span class="math inline">\(p &lt; .05\)</span>.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># Koeffizienten anzeigen</span></span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="kw">tidy</span>(water_medium_model)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term        estimate std.error statistic    p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 (Intercept) -1.11     0.567        -1.95 0.0538    
## 2 temperature  0.173    0.0357        4.85 0.00000469
## 3 sales        0.00119  0.000429      2.77 0.00675</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Modellgüte anzeigen</span></span>
<span id="cb42-2"><a href="#cb42-2"></a><span class="kw">glance</span>(water_medium_model)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.590         0.581  1.31      69.7 1.76e-19     2  -167.  343.  353.
## # ... with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div id="modell-diagnostik-1" class="section level2">
<h2>Modell-Diagnostik</h2>
<p>Wir gehen genauso vor wie oben, wo wir nur einen Prädiktor hatten; alle Diagnostik-Kriterien bleiben bestehen.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># Anzahl der Prädiktoren</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>k &lt;-<span class="st"> </span><span class="dv">2</span></span>
<span id="cb44-3"><a href="#cb44-3"></a></span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="co"># Anzahl der Beobachtungen</span></span>
<span id="cb44-5"><a href="#cb44-5"></a>n &lt;-<span class="st"> </span><span class="kw">nrow</span>(water_park)</span>
<span id="cb44-6"><a href="#cb44-6"></a></span>
<span id="cb44-7"><a href="#cb44-7"></a><span class="co"># Schwelle berechnen</span></span>
<span id="cb44-8"><a href="#cb44-8"></a>hat_threshold &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(k <span class="op">+</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>n</span>
<span id="cb44-9"><a href="#cb44-9"></a></span>
<span id="cb44-10"><a href="#cb44-10"></a><span class="co"># Residuen, Distanzen und Hebelwerte zum Datensatz hinzufügen</span></span>
<span id="cb44-11"><a href="#cb44-11"></a>water_medium_augmented &lt;-<span class="st"> </span><span class="kw">augment</span>(water_medium_model)</span>
<span id="cb44-12"><a href="#cb44-12"></a></span>
<span id="cb44-13"><a href="#cb44-13"></a>water_medium_augmented <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb44-14"><a href="#cb44-14"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb44-15"><a href="#cb44-15"></a>    <span class="dt">diag_resid =</span> <span class="kw">if_else</span>(<span class="kw">abs</span>(.std.resid) <span class="op">&gt;</span><span class="st"> </span><span class="fl">3.29</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb44-16"><a href="#cb44-16"></a>    <span class="dt">diag_cook =</span> <span class="kw">if_else</span>(.cooksd <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb44-17"><a href="#cb44-17"></a>    <span class="dt">diag_hat =</span> <span class="kw">if_else</span>(.hat <span class="op">&gt;</span><span class="st"> </span>hat_threshold, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb44-18"><a href="#cb44-18"></a>    <span class="dt">diag_sum =</span> diag_resid <span class="op">+</span><span class="st"> </span>diag_cook <span class="op">+</span><span class="st"> </span>diag_hat</span>
<span id="cb44-19"><a href="#cb44-19"></a>  ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb44-20"><a href="#cb44-20"></a><span class="st">  </span><span class="kw">filter</span>(diag_sum <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 13
##   beatings temperature sales .fitted .resid .std.resid   .hat .sigma .cooksd
##      &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1       10        39    2661    8.81  1.19       0.939 0.0711   1.31 2.25e-2
## 2        7        35.1  2650    8.13 -1.13      -0.889 0.0639   1.31 1.80e-2
## 3        2        19.7   410    2.80 -0.795     -0.632 0.0769   1.31 1.11e-2
## 4        5        25.3   419    3.78  1.22       1.01  0.140    1.31 5.51e-2
## 5       10        45.6  2837   10.2  -0.168     -0.138 0.129    1.32 9.35e-4
## 6        4        25.4  2335    6.07 -2.07      -1.65  0.0804   1.30 7.92e-2
## # ... with 4 more variables: diag_resid &lt;dbl&gt;, diag_cook &lt;dbl&gt;, diag_hat &lt;dbl&gt;,
## #   diag_sum &lt;dbl&gt;</code></pre>
<p>Dieses Mal finden wir sechs “problematische” Fälle, in denen wieder die Schwelle des Hebelwerts (0.06) leicht überschritten wurde. Wir tun ansonsten ist alles in Ordnung, also werden wir an dieser Stelle keine Maßnahmen ergreifen und dieses Ergebnis für eine eventuelle Diskussion im Hinterkopf behalten.</p>
<p>Natürlich könnten wor auch <code>ggfortify</code> zur Hilfe nehmen und uns diagnostische Plots ausgeben lassen. Auch hier gibt es keine großen Probleme, die Residuen erscheinen homogen, die Daten ans ich normalverteilt und auch bezüglich des Cook-Abstands und den Hebelwerten gibt es keine dramatischen Fälle.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="kw">autoplot</span>(water_medium_model, <span class="dt">which =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</span></code></pre></div>
<p><img src="lineare-regression_files/figure-html/unnamed-chunk-27-1.png" width="2450" style="display: block; margin: auto;" /></p>
</div>
<div id="standardisierte-koeffizienten" class="section level2">
<h2>Standardisierte Koeffizienten</h2>
<p>Wenn wir uns die Koeffizienten anschauen, könnten wir etwas stutzig werden.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a><span class="kw">tidy</span>(water_medium_model)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term        estimate std.error statistic    p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 (Intercept) -1.11     0.567        -1.95 0.0538    
## 2 temperature  0.173    0.0357        4.85 0.00000469
## 3 sales        0.00119  0.000429      2.77 0.00675</code></pre>
<p>Man könnte meinen, dass die Temperatur einen viel größeren Einfluss auf die Anzahl der Schlägereien hätte als der Kiosk-Umsatz, da der Regressionskoeffizient (<span class="math inline">\(b\)</span>) von <code>temperature</code> um ein vielfaches höher ist als der von <code>sales</code>. Dieser Eindruck täuscht aber. Was diese Koeffizienten bedeuten, haben wir bereits geklärt: Erhöhrt man den Prädiktor um eine Einheit, erhöht sich das Kriterium um den Wert des Koeffizienten.</p>
<p>Bei der Interpretation von Koeffizienten muss man bei multiplen Regressionen jedoch etwas aufpassen, denn diese Änderung des Kriteriums gilt nur, <strong>wenn man alle anderen Prädiktoren konstant hält</strong>. Also, mit jedem Grad Durchschnittstemperatur mehr, finden 0.17 Schlägereien statt, <em>wenn man alle anderen Prädiktoren konstant hält.</em> Das macht auch viel Sinn, denn wenn die Durchschnittstemperatur ein Grad höher ist, aber auch der Umsatz des Kiosks gestiegen ist, dann ändert sich das Kriterium ja um den Einfluss von <code>temperature</code> und <code>sales</code> gleichzeitig. Will man den Effekt jedoch isoliert berichten und verstehen, muss man immer angeben, dass dieser Effekt nur so groß ist, wenn alle anderen Prädiktoren <em>konstant gehalten werden.</em></p>
<p>So erkennen wir auch, warum der Einfluss von <code>sales</code> so klein erscheint: Die Skala von <code>sales</code> ist eine komplett andere als die von <code>temperature</code>. Wenn wir uns die deskriptiven Statistiken von oben noch einmal in Errinnerung rufen, ist die Range der Werte von <code>temperature</code> zwischen 11.9 und 45.6 Grad Celsius. Die von <code>sales</code> jedoch zwischen 410 und 2837 Euro. Um den Einfluss von Prädiktoren, die verschiedene Einheiten haben, besser nachvollziehen zu können, kann man die Regressionskoeffizienten <strong>standardisieren</strong>. Diese standardisierten Koeffizienten nennen die meisten dann <span class="math inline">\(\beta\)</span> (im gegensatz zu <span class="math inline">\(b\)</span>). Die Einheit dieser <span class="math inline">\(\beta\)</span> ist dann für alle Prädiktoren identisch (nämlich Standardabwechungen), wodurch man sie besser vergleichen kann.</p>
<p>Dafür kann man einen von zwei Wegen wählen: Entweder alle Variablen bereits vor der Regression standardisieren und die Regression dann “neu” berechnen, oder die Regressionskoeffizienten anhand der Formel <span class="math display">\[\beta_j = b_j \cdot \dfrac{s_{x_j}}{s_y}\]</span> umwandeln. Dabei ist <span class="math inline">\(b_j\)</span> der rohe Koeffizient, <span class="math inline">\(s_{x_i}\)</span> die Standardabweichung des jeweiligen Prädiktors und <span class="math inline">\(s_y\)</span> die Standardabweichung des Kriteriums.</p>
<p>Zusammen mit den deskriptiven Statistiken würden wir in diesem Falle die folgenden standardisierten Koeffizienten erhalten.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>beta_temperature &lt;-<span class="st"> </span><span class="fl">0.173</span> <span class="op">*</span><span class="st"> </span><span class="fl">6.00</span> <span class="op">/</span><span class="st"> </span><span class="fl">2.02</span></span>
<span id="cb49-2"><a href="#cb49-2"></a>beta_sales &lt;-<span class="st"> </span><span class="fl">0.00119</span> <span class="op">*</span><span class="st"> </span><span class="dv">500</span> <span class="op">/</span><span class="st"> </span><span class="fl">2.02</span></span>
<span id="cb49-3"><a href="#cb49-3"></a></span>
<span id="cb49-4"><a href="#cb49-4"></a>beta_temperature</span></code></pre></div>
<pre><code>## [1] 0.5138614</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a>beta_sales</span></code></pre></div>
<pre><code>## [1] 0.2945545</code></pre>
<p>Eine gute Übung ist es jedoch, die Variablen vorher auch mal zu standardisieren und das Modell erneut zu schätzen. Die Funktion, mit der man in R standardisieren kann, ist <code>scale()</code>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="co"># Alle nummerischen Variablen standardisieren</span></span>
<span id="cb53-2"><a href="#cb53-2"></a>water_park_scaled &lt;-<span class="st"> </span>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-3"><a href="#cb53-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb53-4"><a href="#cb53-4"></a>    <span class="kw">across</span>(<span class="kw">where</span>(is.numeric), <span class="op">~</span><span class="st"> </span><span class="kw">scale</span>(.)[,<span class="dv">1</span>], <span class="dt">.names =</span> <span class="st">&quot;scaled_{col}&quot;</span>)</span>
<span id="cb53-5"><a href="#cb53-5"></a>  )</span>
<span id="cb53-6"><a href="#cb53-6"></a></span>
<span id="cb53-7"><a href="#cb53-7"></a><span class="co"># Das neue Modell schätzen</span></span>
<span id="cb53-8"><a href="#cb53-8"></a>water_scaled_model &lt;-<span class="st"> </span><span class="kw">lm</span>(scaled_beatings <span class="op">~</span><span class="st"> </span>scaled_temperature <span class="op">+</span><span class="st"> </span>scaled_sales, <span class="dt">data =</span> water_park_scaled)</span>
<span id="cb53-9"><a href="#cb53-9"></a></span>
<span id="cb53-10"><a href="#cb53-10"></a><span class="co"># Standardisierte Koeffizienten ausgeben lassen</span></span>
<span id="cb53-11"><a href="#cb53-11"></a><span class="kw">tidy</span>(water_scaled_model)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term               estimate std.error statistic    p.value
##   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 (Intercept)        2.53e-16    0.0647  3.91e-15 1.00      
## 2 scaled_temperature 5.14e- 1    0.106   4.85e+ 0 0.00000469
## 3 scaled_sales       2.94e- 1    0.106   2.77e+ 0 0.00675</code></pre>
<p>Die standardisierten Regressionskoeffizienten (<span class="math inline">\(\beta\)</span>) interpretiert man genau so, wie die rohen Koeffizienten (<span class="math inline">\(b\)</span>), außer, dass sich die Einheit der Variablen in Standardabweichungen geändert hat. Erhöht sich die <strong>Temperatur</strong> um eine Standardabweichung, dann erhöht sich die Anzahl der Schlägereien um 0.514 Standardabweichungen. Das kann man mithilfe der Standardabweichungen (siehe unten) wieder in verständliche Einheiten umrechnen. Erhöht sich die Temperatur um eine Standardabweichung (6 Grad Celsius), dann erhöht sich die Anzahl der Schlägereien um <span class="math inline">\(0.514 \cdot 2.02 = 1.04\)</span>, wenn alle anderen Prädiktoren konstant gehalten werden.</p>
<p>Erhöht sich der <strong>Kiosk-Umsatz</strong> um eine Standardabweichung (500 Euro), dann erhöht sich die Anzahl der Schlägereien um <span class="math inline">\(0.294 * 2.02 = 0.59\)</span>. Nun können wir mit Sicherheit sagen, dass die Temperatur einen größeren Einfluss auf die Anzahl der Schlägereien im Schwimmbad hat.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a>water_park <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-2"><a href="#cb55-2"></a><span class="st">  </span><span class="kw">select</span>(beatings, temperature, sales) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-3"><a href="#cb55-3"></a><span class="st">  </span><span class="kw">get_summary_stats</span>(<span class="dt">type =</span> <span class="st">&quot;mean_sd&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   variable        n    mean     sd
##   &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 beatings      100    5.01   2.02
## 2 sales         100 1500.   500.  
## 3 temperature   100   25.0    6.00</code></pre>
</div>
<div id="berichten" class="section level2">
<h2>Berichten</h2>
<p>We found daily temperature and sales to predict the amount of beatings significantly, <span class="math inline">\(F(2, 97) = 69.7, p &lt; .001, R^2_\text{adj} = .581\)</span>. The raw and standardized regression coefficients can be found in the following table.</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#eaqfsxdzym .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#eaqfsxdzym .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#eaqfsxdzym .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#eaqfsxdzym .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#eaqfsxdzym .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#eaqfsxdzym .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#eaqfsxdzym .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#eaqfsxdzym .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#eaqfsxdzym .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#eaqfsxdzym .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#eaqfsxdzym .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#eaqfsxdzym .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#eaqfsxdzym .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#eaqfsxdzym .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#eaqfsxdzym .gt_from_md > :first-child {
  margin-top: 0;
}

#eaqfsxdzym .gt_from_md > :last-child {
  margin-bottom: 0;
}

#eaqfsxdzym .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#eaqfsxdzym .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#eaqfsxdzym .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#eaqfsxdzym .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#eaqfsxdzym .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#eaqfsxdzym .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#eaqfsxdzym .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#eaqfsxdzym .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#eaqfsxdzym .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#eaqfsxdzym .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#eaqfsxdzym .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#eaqfsxdzym .gt_left {
  text-align: left;
}

#eaqfsxdzym .gt_center {
  text-align: center;
}

#eaqfsxdzym .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#eaqfsxdzym .gt_font_normal {
  font-weight: normal;
}

#eaqfsxdzym .gt_font_bold {
  font-weight: bold;
}

#eaqfsxdzym .gt_font_italic {
  font-style: italic;
}

#eaqfsxdzym .gt_super {
  font-size: 65%;
}

#eaqfsxdzym .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="eaqfsxdzym" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1"><em>b</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1"><em>SE</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">&beta;</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1"><em>t</em></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1"><em>p</em></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">(Intercept)</td>
      <td class="gt_row gt_right">&minus;1.107</td>
      <td class="gt_row gt_right">0.567</td>
      <td class="gt_row gt_right">0.000</td>
      <td class="gt_row gt_right">&minus;1.952</td>
      <td class="gt_row gt_right">0.054</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">temperature</td>
      <td class="gt_row gt_right">0.173</td>
      <td class="gt_row gt_right">0.036</td>
      <td class="gt_row gt_right">0.514</td>
      <td class="gt_row gt_right">4.851</td>
      <td class="gt_row gt_right">< .001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">sales</td>
      <td class="gt_row gt_right">0.001</td>
      <td class="gt_row gt_right">0.000</td>
      <td class="gt_row gt_right">0.294</td>
      <td class="gt_row gt_right">2.768</td>
      <td class="gt_row gt_right">0.007</td>
    </tr>
  </tbody>
  
  
</table></div>
</div>
<div id="modellvergleiche" class="section level2">
<h2>Modellvergleiche</h2>
<p>Ist unser Modell mit zwei Prädiktoren eigentlich signifikant besser als ein Modell mit nur einem Prädiktor? Das können wir ganz einfach testen lassen. Zunächst müssen wir die beiden Modelle definieren. Wir betrachten das korrigierte <span class="math inline">\(R^2_\text{adj}\)</span> und stellen eine leichte Verbesserung von .553 (Modell 1) auf .581 (Modell 2) fest. Aber ist dieser Unterschied signifikant?</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>model_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(beatings <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> water_park)</span>
<span id="cb57-2"><a href="#cb57-2"></a></span>
<span id="cb57-3"><a href="#cb57-3"></a>model_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(beatings <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>sales, <span class="dt">data =</span> water_park)</span>
<span id="cb57-4"><a href="#cb57-4"></a></span>
<span id="cb57-5"><a href="#cb57-5"></a><span class="kw">glance</span>(model_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.557         0.553  1.35      123. 4.99e-19     1  -171.  348.  356.
## # ... with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="kw">glance</span>(model_<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.590         0.581  1.31      69.7 1.76e-19     2  -167.  343.  353.
## # ... with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>Diese Frage können wir mit einem Chi-Quadrat-Differenztest berechnen, den R (verwirrenderweise) in der Funktion <code>anova()</code> zur Verfügung stellt.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="kw">anova</span>(model_<span class="dv">1</span>, model_<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: beatings ~ temperature
## Model 2: beatings ~ temperature + sales
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     98 179.38                                
## 2     97 166.24  1    13.133 7.6627 0.006753 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Und wir stellen fest, dass unser Modell durch das Aufnehmen von <code>sales</code> als Prädiktor signifikant verbessert wird, <span class="math inline">\(\chi^2(1) = 7.66, p = .007\)</span>.</p>
</div>
</div>
<div id="literatur" class="section level1 unnumbered">
<h1>Literatur</h1>
<div id="refs" class="references">
<div id="ref-Cook.1982">
<p>Cook, R. D., &amp; Weisberg, S. (1982). <em>Residuals and Influence in Regression</em>. Chapman and Hall.</p>
</div>
<div id="ref-Field.2018">
<p>Field, A. P. (2018). <em>Discovering Statistics using IBM SPSS Statistics</em> (5th ed.). SAGE.</p>
</div>
<div id="ref-Hoaglin.1978">
<p>Hoaglin, D. C., &amp; Welsch, R. E. (1978). The Hat Matrix in Regression and ANOVA. <em>The American Statistician</em>, <em>32</em>(1), 17–22. <a href="https://doi.org/10.1080/00031305.1978.10479237">https://doi.org/10.1080/00031305.1978.10479237</a></p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Manche Autoren empfehlen auch, dass die Hebelwerte nicht größer als <em>drei</em> mal der durchschnittliche Hebelwert sein sollten <span class="citation">(Field, <a href="#ref-Field.2018" role="doc-biblioref">2018</a>)</span><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
