<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>t-Test bei unabhängigen Stichproben</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Chamber of Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Allgemeines
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="software.html">Software</a>
    </li>
    <li>
      <a href="r-basics.html">R Basics</a>
    </li>
    <li>
      <a href="stil.html">Stil</a>
    </li>
    <li>
      <a href="pakete.html">Pakete</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Mittelwerte vergleichen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mittelwerte-vergleichen.html">Überblick</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">t-Tests</li>
    <li>
      <a href="t-test-einstichprobe.html">Bei einer Stichprobe</a>
    </li>
    <li>
      <a href="t-test-unabhaengig.html">Bei unabhängigen Stichproben</a>
    </li>
    <li>
      <a href="t-test-abhaengig.html">Bei abhängigen Stichproben</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ANOVAs</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-question"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="voraussetzungen.html">Voraussetzungen im GLM</a>
    </li>
    <li class="dropdown-header">Zentraler Grenzwertsatz</li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore"><span class="math inline">\(t\)</span>-Test bei unabhängigen Stichproben</h1>

</div>


<p><img src="images/harry-potter-car_r.jpg" /></p>
<p>Begeben wir uns in die Welt der Magie, Muggel und Zauberstäbe; tauchen wir ein in die Welt von Harry Potter <span class="citation">(Rowling, <a href="#ref-Rowling.1997" role="doc-biblioref">1997</a>)</span>. Auch in Hogwarts gibt es viel zu entdecken und statistisch zu entschlüsseln. Vielleicht kennst Du die vier Häuser von Hogwarts: Gryffindor, Hufflepuff, Ravenclaw und Slytherin. Jedem dieser Häuser werden verschiedene Eigenschaften nachgesagt, und jeder Schüler wird ausgehend von seinen Eigenschaften durch den sprechenden Hut einem der Häuser zugeteilt. Genau diese Eigenschaften der Schüler in den Häusern können wir uns nun einmal anschauen.</p>
<div id="pakete" class="section level1">
<h1>Pakete</h1>
<p>Alle Berechnungen und Abbildungen können wir mit unseren <a href="pakete.html">Standardpaketen</a> durchführen. Wir benötigen das <code>tidyverse</code> zum Data Wrangling und zur Visualisierung der Daten. <code>haven</code> benötigen wir für den Import von SPSS-Dateien, <code>rstatix</code> für statistische Analysen und <code>skimr</code> für schnelle deskriptive Statistiken.</p>
<pre class="r"><code>library(tidyverse)
library(haven)
library(rstatix)
library(skimr)</code></pre>
</div>
<div id="beispiel" class="section level1">
<h1>Beispiel</h1>
<p>Es wird spannend, denn wir betrachten die Rivalität der Häuser Griffyndor und Slytherin. Dem Haus Griffyndor werden Tapferkeit, Kühnheit und Ritterlichkeit zugeschrieben – dem Haus Slytherin, naja, eher nicht. Im Datensatz <code>chivalry.sav</code> sind die Ergebnisse eines Persönlichkeitstests zu finden, den alle in Hogwarts eingeschriebenen Bewohner dieser zwei Häuser durchführten, und der das Konstrukt “Ritterlichkeit” erfasst. Der Gesamtwert dieses Tests kann Werte zwischen 0 (keine Richtterlichkeit vorhanden) und 110 (nimmt den Kampf gegen Voldemort auf und empfängt den Tod als einen alten Freund) annehmen.</p>
<pre class="r"><code>chivalry_data &lt;- read_spss(&quot;data/chivalry.sav&quot;)

chivalry_data &lt;- chivalry_data %&gt;% mutate(house = as_factor(house))

chivalry_data</code></pre>
<pre><code>## # A tibble: 80 x 3
##    id    house      chivalry
##    &lt;chr&gt; &lt;fct&gt;         &lt;dbl&gt;
##  1 1     Gryffindor       95
##  2 2     Gryffindor       75
##  3 3     Gryffindor       95
##  4 4     Gryffindor       95
##  5 5     Gryffindor       83
##  6 6     Gryffindor       92
##  7 7     Gryffindor       89
##  8 8     Gryffindor       98
##  9 9     Gryffindor       86
## 10 10    Gryffindor       97
## # ... with 70 more rows</code></pre>
<p>Da wir wieder SPSS-Daten importieren, finden wir für die Variable <code>house</code> wieder den merkwürdigen Datentyp <code>&lt;dbl+lbl&gt;</code> vor. Hier ist R nur mehr als freundlich zu uns, indem es uns beides, die Werte-Levels und -Labels gleichzeitig anzeigt Für die Analysen benötigen wir jedoch nur die Labels als ordentliche Faktoren. Das beheben wir mit der Funktion <code>as_factor()</code> (siehe auch die Seite zum <a href="data-wrangling.html">Data Wrangling</a>).</p>
<div id="voraussetzungen" class="section level2">
<h2>Voraussetzungen</h2>
<p>Es gelten die üblichen <a href="voraussetzungen.html">Voraussetzungen des GLM</a>.</p>
</div>
<div id="eda" class="section level2">
<h2>EDA</h2>
<p>Auch hier betrachten wir die Daten erstmal, bevor wir irgendwelche Analysen durchführen. Beobachtet man verschiedene Gruppen, macht es Sinn, die Ausgabe der statistischen Kennwerte für jede Gruppe durchzuführen.</p>
<pre class="r"><code>chivalry_data %&gt;% 
  group_by(house) %&gt;% 
  skim()</code></pre>
<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">80</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">house</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="left">house</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">id</td>
<td align="left">Gryffindor</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">42</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">id</td>
<td align="left">Slytherin</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">38</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="left">house</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">chivalry</td>
<td align="left">Gryffindor</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">92.29</td>
<td align="right">6.86</td>
<td align="right">75</td>
<td align="right">89</td>
<td align="right">92.0</td>
<td align="right">96.5</td>
<td align="right">105</td>
<td align="left">▂▂▇▅▃</td>
</tr>
<tr class="even">
<td align="left">chivalry</td>
<td align="left">Slytherin</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">48.08</td>
<td align="right">8.94</td>
<td align="right">26</td>
<td align="right">42</td>
<td align="right">47.5</td>
<td align="right">53.0</td>
<td align="right">72</td>
<td align="left">▁▅▇▂▁</td>
</tr>
</tbody>
</table>
<p>Wir sehen einen eindeutigen Trend dahingehend, dass sich die Mitglieder Griffyndors als deutlicher ritterlicher einschätzen (<span class="math inline">\(M = 92.3, SD = 6.86\)</span>) als die Mitglieder der Hauses Slytherin (<span class="math inline">\(M = 48.1, SD = 8.94\)</span>). Auch in der Abbildung sehen wir diesen Unterschied deutlich. Die Boxplots (C) zeigen uns insgesamt 4 Outlier, zwei in jedem Haus. Die könnte man bei Bedarf entfernen, wir belassen es jedoch dabei und fahren fort, auch weil die Varianz der Daten in beiden Häusern ähnlich zu sein scheint. Außerdem sehen die Daten gut normalverteilt aus, was wir anhand der Kerndichteschätzungen (= “geglättetes” Histogramm in A) und dem QQ-Plot (B) erkennen können.</p>
<p><img src="t-test-unabhaengig_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Wer auf Tests zur Überprüfung der Voraussetzungen besteht, also dem Vorgehen, von dem ich wieder <a href="voraussetzungen.html">entschieden abrate</a>), der kann diese natürlich durchführen. Wichtig ist dabei zu beachten, dass der Test der Daten “auf Normalverteilung” pro Haus, bzw. pro Gruppe, durchgeführt werden muss.</p>
<pre class="r"><code>chivalry_data %&gt;% 
  group_by(house) %&gt;% 
  shapiro_test(chivalry)</code></pre>
<pre><code>## # A tibble: 2 x 4
##   house      variable statistic     p
##   &lt;fct&gt;      &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 Gryffindor chivalry     0.972 0.382
## 2 Slytherin  chivalry     0.980 0.717</code></pre>
<pre class="r"><code>chivalry_data %&gt;% 
  levene_test(chivalry ~ house)</code></pre>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic     p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1     1    78      2.19 0.143</code></pre>
<p>Auch anhand der Tests können wir in diesem Falle (alle <span class="math inline">\(p &gt; .05\)</span>) festhalten, dass die Daten nicht signifikant von einer theoretischen Normalverteilung abweichen und die Varianzen in beiden Häusern auch nicht signifikant verschieden sind. Diese Ergebnisse heißen jedoch <em>nicht</em>, dass die Daten normalverteilt und die Varianzen gleich sind.</p>
</div>
<div id="durchführung" class="section level2">
<h2>Durchführung</h2>
<pre class="r"><code>chivalry_data %&gt;% 
  t_test(chivalry ~ house)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   .y.      group1     group2       n1    n2 statistic    df        p
## * &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1 chivalry Gryffindor Slytherin    42    38      24.6  69.2 5.98e-36</code></pre>
<p>Ja, die beiden Mitglieder der Häuser unterscheiden sich in ihrer selbst eingeschätzten Ritterlichkeit signifikant voneinander, da <span class="math inline">\(p &lt; 0.05\)</span> ist. Wer sich die Daten in einem anderen Statistikprogramm vorgenommen und mitgerechnet hat, vielleicht sogar direkt in SPSS, der wird feststellen, dass die Werte etwas von seinen abweichen. Das liegt daran, dass R standardmäßig gar nicht den traditionellen <span class="math inline">\(t\)</span>-Test (auch Students <span class="math inline">\(t\)</span>-Test genannt) berechnet, sondern den <strong>Welchs-<span class="math inline">\(t\)</span>-Test</strong>. Den kennen viele Psychologie-Studenten eigentlich als Alternative zum <span class="math inline">\(t\)</span>-Test, wenn die Voraussetzungen der Normalverteilung und Varianzhomogenität verletzt sind. Auf die Prüfung dieser beiden Annahmen kann man eigentlich gänzlich verzichten und standardmäßigdirekt den Welch-Test durchführen <span class="citation">(Rasch et al., <a href="#ref-Rasch.2011" role="doc-biblioref">2011</a>; Ruxton, <a href="#ref-Ruxton.2006" role="doc-biblioref">2006</a>)</span>, so, wie R es auch anbietet. Wer dennoch unbedingt den “richtigen” <span class="math inline">\(t\)</span>-Test haben möchte, gibt einfach ein zusätzliches Argument an und schon decken sich alle Ergebnisse.</p>
<pre class="r"><code>chivalry_data %&gt;% 
  t_test(chivalry ~ house, var.equal = TRUE)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   .y.      group1     group2       n1    n2 statistic    df        p
## * &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1 chivalry Gryffindor Slytherin    42    38      24.9    78 6.41e-39</code></pre>
<p>Bei Gruppenunterschieden ist nicht nur interessant, ob sich diese statistisch signifikant voneinander unterscheiden; vor allem interessiert uns die Größe des Effekts, also die Effektstärke. Auch diese lässt sich einfach berechnen. Hier sollte man immer das Argument <code>hedges.correction = TRUE</code> angeben, da Cohens <span class="math inline">\(d\)</span> von Haus aus positiv verzerrt ist <span class="citation">(Hedges &amp; Olkin, <a href="#ref-Hedges.1985" role="doc-biblioref">1985</a>)</span>. Entgegen dem Namen des Befehls (<code>cohens_d()</code>) erhalten wir so nicht Cohens <span class="math inline">\(d\)</span>, sondern Hedges’ <span class="math inline">\(g\)</span>.</p>
<pre class="r"><code>chivalry_data %&gt;% 
  cohens_d(chivalry ~ house, hedges.correction = TRUE)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   .y.      group1     group2    effsize    n1    n2 magnitude
## * &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;ord&gt;    
## 1 chivalry Gryffindor Slytherin    5.49    42    38 large</code></pre>
</div>
<div id="berichten" class="section level2">
<h2>Berichten</h2>
<p>Members of the Hogwarts house “Gryffindor” yielded greater scores on a test estimating chivalry as opposed to members of house “Slytherin”. The mean difference of 44.2 points was statistically significant, <span class="math inline">\(t(69.2) = 24.6, p &lt; .001\)</span> with an effect size of Hedges’ <span class="math inline">\(g = 5.50\)</span>, indicating a huge effect.</p>
</div>
</div>
<div id="robuste-alternativen" class="section level1">
<h1>Robuste Alternativen</h1>
<p>Folgen.</p>
</div>
<div id="aus-der-praxis" class="section level1">
<h1>Aus der Praxis</h1>
<p>Praxis-Beispiele folgen.</p>
</div>
<div id="literatur" class="section level1 unnumbered">
<h1>Literatur</h1>
<div id="refs" class="references">
<div id="ref-Hedges.1985">
<p>Hedges, L. V., &amp; Olkin, I. (1985). <em>Statistical Methods for Meta-Analysis</em>. Academic Press.</p>
</div>
<div id="ref-Rasch.2011">
<p>Rasch, D., Kubinger, K. D., &amp; Moder, K. (2011). The two-sample t test: pre-testing its assumptions does not pay off. <em>Statistical Papers</em>, <em>52</em>(1), 219–231. <a href="https://doi.org/10.1007/s00362-009-0224-x">https://doi.org/10.1007/s00362-009-0224-x</a></p>
</div>
<div id="ref-Rowling.1997">
<p>Rowling, J. K. (1997). <em>Harry Potter and the Philosopher’s Stone</em>. Bloomsbury.</p>
</div>
<div id="ref-Ruxton.2006">
<p>Ruxton, G. D. (2006). The unequal variance t-test is an underused alternative to Student’s t-test and the Mann–Whitney U test. <em>Behavioral Ecology</em>, <em>17</em>(4), 688–690. <a href="https://doi.org/10.1093/beheco/ark016">https://doi.org/10.1093/beheco/ark016</a></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
